namespace EducationalPlans.Domain 
{
 public class ПараметрыПлана 
{
public System.String id { get; set; }
public System.Int32 rowOrder { get; set; }
public System.String hasChanges { get; set; }
public System.Int32 КодПлана { get; set; }
public System.Int32 count { get; set; }
public System.Boolean Flag_FillTitle { get; set; }
public System.Boolean Flag_SrokO { get; set; }
public System.Int32 SrokOYear { get; set; }
public System.Int32 SrokOMonth { get; set; }
public System.Boolean Flag_OOPItog { get; set; }
public System.Int32 OOPItog { get; set; }
public System.Boolean Flag_OOPyear { get; set; }
public System.Int32 OOPyear { get; set; }
public System.Boolean Flag_ZETdelta { get; set; }
public System.Boolean Flag_DVVpersent { get; set; }
public System.Boolean Flag_DVVpersent1p3 { get; set; }
public System.Int32 DVVpersent30Min { get; set; }
public System.Int32 DVVpersent30Max { get; set; }
public System.Boolean Flag_BasePart { get; set; }
public System.Int32 BasePartMin { get; set; }
public System.Int32 BasePartMax { get; set; }
public System.Boolean Flag_ZETDiscMin { get; set; }
public System.Int32 ZETDiscMin { get; set; }
public System.Boolean Flag_DiscZETIsInt { get; set; }
public System.Boolean Flag_DiscZETYearIsInt { get; set; }
public System.Boolean Flag_ZETExpertTrue { get; set; }
public System.Boolean Flag_DiscZETExpertTrue { get; set; }
public System.Boolean Flag_HinW54 { get; set; }
public System.Int32 HinW54 { get; set; }
public System.Boolean Flag_HinWAudit { get; set; }
public System.Int32 HinWAuditMin { get; set; }
public System.Int32 HinWAuditMax { get; set; }
public System.Boolean Flag_HinWAuditSr { get; set; }
public System.Int32 HinWAuditSrMin { get; set; }
public System.Int32 HinWAuditSrMax { get; set; }
public System.Boolean Flag_Lect { get; set; }
public System.Int32 LectMin { get; set; }
public System.Int32 LectMax { get; set; }
public System.Boolean Flag_Inter { get; set; }
public System.Int32 InterMin { get; set; }
public System.Int32 InterMax { get; set; }
public System.Boolean Flag_ZETAndHoursIsTrue { get; set; }
public System.Boolean Flag_DiscZETAndHoursIsTrue { get; set; }
public System.Boolean Flag_DiscSemZETAndHoursIsTrue { get; set; }
public System.Boolean Flag_AuditAll { get; set; }
public System.Int32 AuditAllMin { get; set; }
public System.Int32 AudetAllMax { get; set; }
public System.Boolean Flag_EqZET36 { get; set; }
public System.Int32 EqZET36 { get; set; }
public System.Boolean Flag_EqZETDis32_38 { get; set; }
public System.Boolean Flag_CntrlEx { get; set; }
public System.Int32 CntrlExMin { get; set; }
public System.Int32 CntrlExMax { get; set; }
public System.Boolean Flag_CntrlExSem { get; set; }
public System.Int32 CntrlExSemMax { get; set; }
public System.Boolean Flag_CntrlZach { get; set; }
public System.Int32 CntrlZachMin { get; set; }
public System.Int32 CntrlZachMax { get; set; }
public System.Boolean Flag_CntrlZachSem { get; set; }
public System.Int32 CntrlZachSemMax { get; set; }
public System.Boolean Flag_CntrlKP { get; set; }
public System.Int32 CntrlKPMax { get; set; }
public System.Boolean Flag_CntrlKR { get; set; }
public System.Int32 CntrlKRMax { get; set; }
public System.Boolean Flag_CntrlExHours { get; set; }
public System.Int32 CntrlExHoursMin { get; set; }
public System.Int32 CntrlExHoursMax { get; set; }
public System.Boolean Flag_CntrlHasHours { get; set; }
public System.Boolean Flag_CntrlHasHoursItogS { get; set; }
public System.Boolean Flag_HoursCouple { get; set; }
public System.Boolean Flag_HoursKratNed { get; set; }
public System.Boolean Flag_HoursKratNedFirstPos { get; set; }
public System.Boolean Flag_HoursKSRForKR { get; set; }
public System.Int32 HoursKSRForKRMin { get; set; }
public System.Int32 HoursKSRForKRMax { get; set; }
public System.Boolean Flag_HoursKSRForKP { get; set; }
public System.Int32 HoursKSRForKPMin { get; set; }
public System.Int32 HoursKSRForKPMax { get; set; }
public System.Boolean Flag_HoursKSRpSRS { get; set; }
public System.Int32 HoursKSRpSRSMin { get; set; }
public System.Int32 HoursKSRpSRSMax { get; set; }
public System.Boolean Flag_HoursAudSemTrue { get; set; }
public System.Boolean Flag_HoursAudSemTrueWithKSR { get; set; }
public System.Boolean Flag_HoursSRSSemTrue { get; set; }
public System.Boolean Flag_HoursSRSSemTrueWithKSR { get; set; }
public System.Boolean Flag_PracticsWeeksCorrrect { get; set; }
public System.Boolean Flag_HolidaysWeeks { get; set; }
public System.Int32 HolidaysWeeksMin { get; set; }
public System.Int32 HolidaysWeeksMax { get; set; }
public System.Boolean Flag_HolidaysWinterWeeks { get; set; }
public System.Int32 HolidaysWinterWeeksMin { get; set; }
public System.Int32 HolidaysWinterWeeksMax { get; set; }
public System.Boolean Flag_DiscAltTrue { get; set; }
public System.Boolean Flag_DiscDiscMust { get; set; }
public System.Boolean Flag_DiscCompTrue { get; set; }
public System.Boolean Flag_DiscCompDBTrue { get; set; }
public System.Boolean Flag_DiscCompHandMadeTrue { get; set; }
public System.Int32 DiscCompHandMadeOK { get; set; }
public System.Int32 DiscCompHandMadePK { get; set; }
public System.Boolean Flag_BaseDiscCompTrue { get; set; }
public System.Boolean Flag_DiscMinOneCompTrue { get; set; }
public System.Boolean Flag_DiscFatalCoincidence { get; set; }
public System.Boolean Flag_DiscKafTrue { get; set; }
public System.Boolean Flag_DiscPhysCZET { get; set; }
public System.Int32 DiscPhysCZET { get; set; }
public System.Boolean Flag_DiscPhysCHours { get; set; }
public System.Int32 DiscPhysCHours { get; set; }
public System.Boolean Flag_DiscPhysCHoursPractices { get; set; }
public System.Int32 DiscPhysCHoursPractices { get; set; }
public System.Boolean Flag_DiscJustificationZETLocationForCourses { get; set; }
public System.Int32 DiscJustificationZETLocationForCoursesPosition { get; set; }
public System.Int32 DiscJustificationZETLocationForCoursesOneZET { get; set; }
public System.Boolean Flag_ZET_Pereat { get; set; }
public System.Int32 ZET_Pereat { get; set; }
public System.Int32 HinWEx54 { get; set; }
public System.Boolean ShowIndex { get; set; }
public System.Boolean ShowCmpt { get; set; }
public System.Boolean ShowKafCode { get; set; }
public System.Boolean ShowZETExp { get; set; }
public System.Boolean ShowZETFact { get; set; }
public System.Boolean ShowHinZET { get; set; }
public System.Boolean ShowHFromZET { get; set; }
public System.Boolean ShowHFromPlan { get; set; }
public System.Boolean ShowItogoKontact { get; set; }
public System.Boolean ShowItogoAud { get; set; }
public System.Boolean ShowItogoSRS { get; set; }
public System.Boolean ShowItogoCtrl { get; set; }
public System.Boolean ShowItogoInter { get; set; }
public System.Boolean ShowItogoDist { get; set; }
public System.Boolean ShowKafName { get; set; }
public System.Boolean ShowZETPereatt { get; set; }
public System.Boolean ShowZETOstIzuch { get; set; }
public System.Boolean ShowHoursPereatt { get; set; }
public System.Boolean ShowHoursOstIzuch { get; set; }
public System.Boolean ShowZETIm { get; set; }
public System.Boolean ShowHItogIm { get; set; }
public System.Boolean ShowHKontactIm { get; set; }
public System.Boolean ShowHAudIm { get; set; }
public System.Boolean ShowHInterIm { get; set; }
public System.Boolean ShowHDistIm { get; set; }
public System.Boolean ViewHinWeek { get; set; }
public System.Boolean FlagSaveParamView { get; set; }
public System.Boolean IsEqualsDV { get; set; }
public System.Boolean IsNotEqualsVZ { get; set; }
public System.Boolean IsNotEqualsCtrl { get; set; }
public System.Boolean IsNotEqualsOther { get; set; }
public System.Boolean IsSetEquals { get; set; }
public System.Int32 NormHoursEx { get; set; }
public System.Int32 NormHoursZ { get; set; }
public System.Int32 NormHoursZo { get; set; }
public System.Boolean ZETDiscMinNotDB { get; set; }
public System.Boolean ZETDiscMinNotRazdel { get; set; }
public System.Boolean FlagKRAll { get; set; }
public System.Boolean FlagKPAll { get; set; }
public System.Int32 KRAllCount { get; set; }
public System.Int32 KPAllCount { get; set; }
public System.Boolean FlagKRYear { get; set; }
public System.Boolean FlagKPYear { get; set; }
public System.Boolean FlagKRSem { get; set; }
public System.Boolean FlagKPSem { get; set; }
public System.Int32 KRSemCount { get; set; }
public System.Int32 KPSemCount { get; set; }
public System.Boolean KontSemSelect { get; set; }
public System.Boolean IsEqualsCmpt { get; set; }
public System.Boolean IsNotEqualsOK { get; set; }
public System.Boolean IsNotEqualsOPK { get; set; }
public System.Boolean IsNotEqualsPK { get; set; }
public System.Boolean FlagAssistKanik { get; set; }
public System.Boolean Flag_CntrlHasHoursItogWithMod { get; set; }
public System.Boolean FlagVisibleAudN { get; set; }
public System.Boolean IsNotIncludePhizk { get; set; }
public System.Boolean IsNotIncludeFacult { get; set; }
public System.Boolean IsEqualsPersons { get; set; }
public System.Boolean DifPrInTabPract { get; set; }
public System.Boolean DifPrInSes { get; set; }
public System.Boolean OnlyGinGYP { get; set; }
public System.Boolean YPrWithTO { get; set; }
public System.Boolean IsWithoutZE { get; set; }
public System.Int32 UpdIndex { get; set; }
public System.Boolean GIAforProfil { get; set; }
public System.Boolean CmptWithoutGIA { get; set; }
public System.Boolean ElectDiscInBasePart { get; set; }
public System.Boolean IsEqualsProfSt { get; set; }
public System.Int32 SesViewOption { get; set; }
public System.Boolean FlagLecOP { get; set; }
public System.Int32 MaxLecOP { get; set; }
public System.Boolean FlagSemOP { get; set; }
public System.Int32 MaxSemOP { get; set; }
public System.Boolean NoCmptInHeadDVB { get; set; }
public System.Int32 TypeHours { get; set; }
public System.Boolean FlagIsFacult { get; set; }
public System.Boolean FlagCmptPractics { get; set; }
public System.Boolean FlagMinBase { get; set; }
public System.Int32 MinPercBase { get; set; }
public System.Boolean Flag_OOPYearNew { get; set; }
public System.Int32 OOPYearNew { get; set; }
}
}