//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_forum_read
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long forumid { get; set; }
        public long discussionid { get; set; }
        public long postid { get; set; }
        public long firstread { get; set; }
        public long lastread { get; set; }
    }
}
