//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_mnetservice_enrol_courses
    {
        public long id { get; set; }
        public long hostid { get; set; }
        public long remoteid { get; set; }
        public long categoryid { get; set; }
        public string categoryname { get; set; }
        public long sortorder { get; set; }
        public string fullname { get; set; }
        public string shortname { get; set; }
        public string idnumber { get; set; }
        public string summary { get; set; }
        public Nullable<short> summaryformat { get; set; }
        public long startdate { get; set; }
        public long roleid { get; set; }
        public string rolename { get; set; }
    }
}
