//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_departments
    {
        public long id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<long> managerid { get; set; }
        public long leaddepid { get; set; }
        public Nullable<long> addressid { get; set; }
        public string zone { get; set; }
        public string status { get; set; }
        public string path { get; set; }
        public Nullable<long> depth { get; set; }
    }
}
