//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_survey_answers
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long survey { get; set; }
        public long question { get; set; }
        public long time { get; set; }
        public string answer1 { get; set; }
        public string answer2 { get; set; }
    }
}
