//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_grading_definitions
    {
        public long id { get; set; }
        public long areaid { get; set; }
        public string method { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<short> descriptionformat { get; set; }
        public long status { get; set; }
        public Nullable<long> copiedfromid { get; set; }
        public long timecreated { get; set; }
        public long usercreated { get; set; }
        public long timemodified { get; set; }
        public long usermodified { get; set; }
        public Nullable<long> timecopied { get; set; }
        public string options { get; set; }
    }
}
