//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_user_info_field
    {
        public long id { get; set; }
        public string shortname { get; set; }
        public string name { get; set; }
        public string datatype { get; set; }
        public string description { get; set; }
        public short descriptionformat { get; set; }
        public long categoryid { get; set; }
        public long sortorder { get; set; }
        public short required { get; set; }
        public short locked { get; set; }
        public short visible { get; set; }
        public short forceunique { get; set; }
        public short signup { get; set; }
        public string defaultdata { get; set; }
        public short defaultdataformat { get; set; }
        public string param1 { get; set; }
        public string param2 { get; set; }
        public string param3 { get; set; }
        public string param4 { get; set; }
        public string param5 { get; set; }
    }
}
