//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_positions
    {
        public long id { get; set; }
        public long blockinstanceid { get; set; }
        public long contextid { get; set; }
        public string pagetype { get; set; }
        public string subpage { get; set; }
        public short visible { get; set; }
        public string region { get; set; }
        public long weight { get; set; }
    }
}
