//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_context
    {
        public long id { get; set; }
        public long contextlevel { get; set; }
        public long instanceid { get; set; }
        public string path { get; set; }
        public short depth { get; set; }
    }
}
