//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_ages
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<long> begindate { get; set; }
        public Nullable<long> enddate { get; set; }
        public Nullable<short> eduweeks { get; set; }
        public Nullable<long> departmentid { get; set; }
        public Nullable<long> previousid { get; set; }
        public string status { get; set; }
        public int schdays { get; set; }
        public string schedudays { get; set; }
        public int schstartdaynum { get; set; }
    }
}
