//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_sync
    {
        public long id { get; set; }
        public string downptype { get; set; }
        public string downpcode { get; set; }
        public string downsubstorage { get; set; }
        public string downid { get; set; }
        public string upptype { get; set; }
        public string uppcode { get; set; }
        public string upsubstorage { get; set; }
        public string upid { get; set; }
        public string direct { get; set; }
        public Nullable<long> lasttime { get; set; }
        public string lastoperation { get; set; }
        public string downhash { get; set; }
        public string uphash { get; set; }
    }
}
