//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_scoes_track
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long scormid { get; set; }
        public long scoid { get; set; }
        public long attempt { get; set; }
        public string element { get; set; }
        public string value { get; set; }
        public long timemodified { get; set; }
    }
}
