//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_book_chapters
    {
        public long id { get; set; }
        public long bookid { get; set; }
        public long pagenum { get; set; }
        public long subchapter { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public short contentformat { get; set; }
        public short hidden { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string importsrc { get; set; }
    }
}
