//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_feedback
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public short anonymous { get; set; }
        public short email_notification { get; set; }
        public short multiple_submit { get; set; }
        public short autonumbering { get; set; }
        public string site_after_submit { get; set; }
        public string page_after_submit { get; set; }
        public short page_after_submitformat { get; set; }
        public short publish_stats { get; set; }
        public long timeopen { get; set; }
        public long timeclose { get; set; }
        public long timemodified { get; set; }
        public short completionsubmit { get; set; }
    }
}
