//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_forum_discussions
    {
        public long id { get; set; }
        public long course { get; set; }
        public long forum { get; set; }
        public string name { get; set; }
        public long firstpost { get; set; }
        public long userid { get; set; }
        public long groupid { get; set; }
        public short assessed { get; set; }
        public long timemodified { get; set; }
        public long usermodified { get; set; }
        public long timestart { get; set; }
        public long timeend { get; set; }
        public short pinned { get; set; }
    }
}
