//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_log_queries
    {
        public long id { get; set; }
        public int qtype { get; set; }
        public string sqltext { get; set; }
        public string sqlparams { get; set; }
        public int error { get; set; }
        public string info { get; set; }
        public string backtrace { get; set; }
        public decimal exectime { get; set; }
        public long timelogged { get; set; }
    }
}
