//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_cache_filters
    {
        public long id { get; set; }
        public string filter { get; set; }
        public long version { get; set; }
        public string md5key { get; set; }
        public string rawtext { get; set; }
        public long timemodified { get; set; }
    }
}
