//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_backup_courses
    {
        public long id { get; set; }
        public long courseid { get; set; }
        public long laststarttime { get; set; }
        public long lastendtime { get; set; }
        public string laststatus { get; set; }
        public long nextstarttime { get; set; }
    }
}
