//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_course_categories
    {
        public long id { get; set; }
        public string name { get; set; }
        public string idnumber { get; set; }
        public string description { get; set; }
        public short descriptionformat { get; set; }
        public long parent { get; set; }
        public long sortorder { get; set; }
        public long coursecount { get; set; }
        public short visible { get; set; }
        public short visibleold { get; set; }
        public long timemodified { get; set; }
        public long depth { get; set; }
        public string path { get; set; }
        public string theme { get; set; }
    }
}
