//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_educations
    {
        public long id { get; set; }
        public long personid { get; set; }
        public Nullable<long> organizationid { get; set; }
        public Nullable<long> edulevel { get; set; }
        public Nullable<long> edydoctype { get; set; }
        public string edudoccode { get; set; }
        public string edudocserial { get; set; }
        public string edudocnum { get; set; }
        public string edudocdate { get; set; }
        public Nullable<long> startdate { get; set; }
        public Nullable<long> finishdate { get; set; }
        public string comment { get; set; }
    }
}
