//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_achievementcats
    {
        public long id { get; set; }
        public string name { get; set; }
        public long parentid { get; set; }
        public Nullable<long> departmentid { get; set; }
        public long sortorder { get; set; }
        public short affectrating { get; set; }
        public long createdate { get; set; }
        public string status { get; set; }
    }
}
