//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_question_attempts
    {
        public long id { get; set; }
        public long questionusageid { get; set; }
        public long slot { get; set; }
        public string behaviour { get; set; }
        public long questionid { get; set; }
        public long variant { get; set; }
        public decimal maxmark { get; set; }
        public decimal minfraction { get; set; }
        public decimal maxfraction { get; set; }
        public short flagged { get; set; }
        public string questionsummary { get; set; }
        public string rightanswer { get; set; }
        public string responsesummary { get; set; }
        public long timemodified { get; set; }
    }
}
