//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_chat_users
    {
        public long id { get; set; }
        public long chatid { get; set; }
        public long userid { get; set; }
        public long groupid { get; set; }
        public string version { get; set; }
        public string ip { get; set; }
        public long firstping { get; set; }
        public long lastping { get; set; }
        public long lastmessageping { get; set; }
        public string sid { get; set; }
        public long course { get; set; }
        public string lang { get; set; }
    }
}
