//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_invitems
    {
        public long id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string serialnum { get; set; }
        public string type { get; set; }
        public long count { get; set; }
        public Nullable<long> termofuse { get; set; }
        public Nullable<long> dateentry { get; set; }
        public Nullable<long> datewriteoff { get; set; }
        public Nullable<long> invcategoryid { get; set; }
        public long departmentid { get; set; }
        public Nullable<long> invsetid { get; set; }
        public Nullable<long> setorderid { get; set; }
        public Nullable<long> outorderid { get; set; }
        public string status { get; set; }
    }
}
