//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_offlinequiz_scanned_p_pages
    {
        public long id { get; set; }
        public long offlinequizid { get; set; }
        public Nullable<short> listnumber { get; set; }
        public string filename { get; set; }
        public long time { get; set; }
        public string status { get; set; }
        public string error { get; set; }
    }
}
