//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_modules
    {
        public long id { get; set; }
        public string name { get; set; }
        public long cron { get; set; }
        public long lastcron { get; set; }
        public string search { get; set; }
        public short visible { get; set; }
    }
}
