//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_programmsbcs
    {
        public long id { get; set; }
        public Nullable<long> contractid { get; set; }
        public Nullable<long> programmid { get; set; }
        public string edutype { get; set; }
        public string eduform { get; set; }
        public string freeattendance { get; set; }
        public Nullable<long> agroupid { get; set; }
        public Nullable<short> agenum { get; set; }
        public Nullable<long> departmentid { get; set; }
        public string status { get; set; }
        public Nullable<long> datestart { get; set; }
        public Nullable<long> dateadd { get; set; }
        public string certificatenum { get; set; }
        public string certificateform { get; set; }
        public Nullable<long> certificatedate { get; set; }
        public Nullable<long> certificateorderid { get; set; }
        public Nullable<long> dateend { get; set; }
        public double salfactor { get; set; }
    }
}
