//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_competency_evidence
    {
        public long id { get; set; }
        public long usercompetencyid { get; set; }
        public long contextid { get; set; }
        public short action { get; set; }
        public Nullable<long> actionuserid { get; set; }
        public string descidentifier { get; set; }
        public string desccomponent { get; set; }
        public string desca { get; set; }
        public string url { get; set; }
        public Nullable<long> grade { get; set; }
        public string note { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long usermodified { get; set; }
    }
}
