//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_assignfeedback_editpdf_cmnt
    {
        public long id { get; set; }
        public long gradeid { get; set; }
        public Nullable<long> x { get; set; }
        public Nullable<long> y { get; set; }
        public Nullable<long> width { get; set; }
        public string rawtext { get; set; }
        public long pageno { get; set; }
        public string colour { get; set; }
        public short draft { get; set; }
    }
}
