//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_competency
    {
        public long id { get; set; }
        public string shortname { get; set; }
        public string description { get; set; }
        public short descriptionformat { get; set; }
        public string idnumber { get; set; }
        public long competencyframeworkid { get; set; }
        public long parentid { get; set; }
        public string path { get; set; }
        public long sortorder { get; set; }
        public string ruletype { get; set; }
        public short ruleoutcome { get; set; }
        public string ruleconfig { get; set; }
        public Nullable<long> scaleid { get; set; }
        public string scaleconfiguration { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public Nullable<long> usermodified { get; set; }
    }
}
