//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_role_capabilities
    {
        public long id { get; set; }
        public long contextid { get; set; }
        public long roleid { get; set; }
        public string capability { get; set; }
        public long permission { get; set; }
        public long timemodified { get; set; }
        public long modifierid { get; set; }
    }
}
