//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_instances
    {
        public long id { get; set; }
        public string blockname { get; set; }
        public long parentcontextid { get; set; }
        public short showinsubcontexts { get; set; }
        public string pagetypepattern { get; set; }
        public string subpagepattern { get; set; }
        public string defaultregion { get; set; }
        public long defaultweight { get; set; }
        public string configdata { get; set; }
    }
}
