//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_choice
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public short publish { get; set; }
        public short showresults { get; set; }
        public short display { get; set; }
        public short allowupdate { get; set; }
        public short allowmultiple { get; set; }
        public short showunanswered { get; set; }
        public short includeinactive { get; set; }
        public short limitanswers { get; set; }
        public long timeopen { get; set; }
        public long timeclose { get; set; }
        public short showpreview { get; set; }
        public long timemodified { get; set; }
        public short completionsubmit { get; set; }
    }
}
