//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_assignment_upgrade
    {
        public long id { get; set; }
        public long oldcmid { get; set; }
        public long oldinstance { get; set; }
        public long newcmid { get; set; }
        public long newinstance { get; set; }
        public long timecreated { get; set; }
    }
}
