//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_quiz_slots
    {
        public long id { get; set; }
        public long slot { get; set; }
        public long quizid { get; set; }
        public long page { get; set; }
        public short requireprevious { get; set; }
        public long questionid { get; set; }
        public decimal maxmark { get; set; }
    }
}
