//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_upgrade_log
    {
        public long id { get; set; }
        public long type { get; set; }
        public string plugin { get; set; }
        public string version { get; set; }
        public string targetversion { get; set; }
        public string info { get; set; }
        public string details { get; set; }
        public string backtrace { get; set; }
        public long userid { get; set; }
        public long timemodified { get; set; }
    }
}
