//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_qtype_essay_options
    {
        public long id { get; set; }
        public long questionid { get; set; }
        public string responseformat { get; set; }
        public short responserequired { get; set; }
        public short responsefieldlines { get; set; }
        public short attachments { get; set; }
        public short attachmentsrequired { get; set; }
        public string graderinfo { get; set; }
        public short graderinfoformat { get; set; }
        public string responsetemplate { get; set; }
        public short responsetemplateformat { get; set; }
    }
}
