//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_offlinequiz_hotspots
    {
        public long id { get; set; }
        public long scannedpageid { get; set; }
        public string name { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
        public Nullable<short> blank { get; set; }
        public long time { get; set; }
    }
}
