//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_teachers
    {
        public long id { get; set; }
        public Nullable<long> appointmentid { get; set; }
        public Nullable<long> programmitemid { get; set; }
        public Nullable<long> departmentid { get; set; }
        public Nullable<decimal> worktime { get; set; }
        public string status { get; set; }
    }
}
