//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_forum
    {
        public long id { get; set; }
        public long course { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public long assessed { get; set; }
        public long assesstimestart { get; set; }
        public long assesstimefinish { get; set; }
        public long scale { get; set; }
        public long maxbytes { get; set; }
        public long maxattachments { get; set; }
        public short forcesubscribe { get; set; }
        public short trackingtype { get; set; }
        public short rsstype { get; set; }
        public short rssarticles { get; set; }
        public long timemodified { get; set; }
        public long warnafter { get; set; }
        public long blockafter { get; set; }
        public long blockperiod { get; set; }
        public int completiondiscussions { get; set; }
        public int completionreplies { get; set; }
        public int completionposts { get; set; }
        public short displaywordcount { get; set; }
    }
}
