//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lti_tool_proxies
    {
        public long id { get; set; }
        public string name { get; set; }
        public string regurl { get; set; }
        public short state { get; set; }
        public string guid { get; set; }
        public string secret { get; set; }
        public string vendorcode { get; set; }
        public string capabilityoffered { get; set; }
        public string serviceoffered { get; set; }
        public string toolproxy { get; set; }
        public long createdby { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
