//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_cache_flags
    {
        public long id { get; set; }
        public string flagtype { get; set; }
        public string name { get; set; }
        public long timemodified { get; set; }
        public string value { get; set; }
        public long expiry { get; set; }
    }
}
