//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_external_tokens
    {
        public long id { get; set; }
        public string token { get; set; }
        public short tokentype { get; set; }
        public long userid { get; set; }
        public long externalserviceid { get; set; }
        public string sid { get; set; }
        public long contextid { get; set; }
        public long creatorid { get; set; }
        public string iprestriction { get; set; }
        public Nullable<long> validuntil { get; set; }
        public long timecreated { get; set; }
        public Nullable<long> lastaccess { get; set; }
    }
}
