//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_achievementins
    {
        public long id { get; set; }
        public long achievementid { get; set; }
        public long userid { get; set; }
        public Nullable<long> moderatorid { get; set; }
        public long timecreated { get; set; }
        public long timechecked { get; set; }
        public Nullable<double> userpoints { get; set; }
        public string data { get; set; }
        public string status { get; set; }
    }
}
