//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_checklist
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public Nullable<short> useritemsallowed { get; set; }
        public Nullable<short> teacheredit { get; set; }
        public string theme { get; set; }
        public Nullable<short> duedatesoncalendar { get; set; }
        public Nullable<short> teachercomments { get; set; }
        public long maxgrade { get; set; }
        public Nullable<short> autopopulate { get; set; }
        public Nullable<short> autoupdate { get; set; }
        public Nullable<long> completionpercent { get; set; }
        public Nullable<short> emailoncomplete { get; set; }
        public Nullable<short> lockteachermarks { get; set; }
    }
}
