//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_accentryes
    {
        public long id { get; set; }
        public long fromid { get; set; }
        public long toid { get; set; }
        public double amount { get; set; }
        public long orderid { get; set; }
        public int createdate { get; set; }
        public int date { get; set; }
        public string extentryopts { get; set; }
        public string extentryoptshash { get; set; }
        public string about { get; set; }
        public string status { get; set; }
    }
}
