//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_auth_otoauth
    {
        public long id { get; set; }
        public long userid { get; set; }
        public string service { get; set; }
        public string remoteuserid { get; set; }
        public Nullable<long> datacreate { get; set; }
        public Nullable<long> lastaccess { get; set; }
        public Nullable<long> active { get; set; }
        public Nullable<long> cron { get; set; }
        public Nullable<long> lastcron { get; set; }
    }
}
