//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_tags
    {
        public long id { get; set; }
        public string @class { get; set; }
        public long parentid { get; set; }
        public long ownerid { get; set; }
        public long departmentid { get; set; }
        public string options { get; set; }
        public long cron { get; set; }
        public Nullable<long> crondone { get; set; }
        public string cronstatus { get; set; }
        public long cronrepeate { get; set; }
        public string about { get; set; }
        public string code { get; set; }
        public string alias { get; set; }
        public string status { get; set; }
    }
}
