//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshop
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public string instructauthors { get; set; }
        public short instructauthorsformat { get; set; }
        public string instructreviewers { get; set; }
        public short instructreviewersformat { get; set; }
        public long timemodified { get; set; }
        public Nullable<short> phase { get; set; }
        public Nullable<short> useexamples { get; set; }
        public Nullable<short> usepeerassessment { get; set; }
        public Nullable<short> useselfassessment { get; set; }
        public Nullable<decimal> grade { get; set; }
        public Nullable<decimal> gradinggrade { get; set; }
        public string strategy { get; set; }
        public string evaluation { get; set; }
        public Nullable<short> gradedecimals { get; set; }
        public Nullable<short> nattachments { get; set; }
        public string submissionfiletypes { get; set; }
        public Nullable<short> latesubmissions { get; set; }
        public Nullable<long> maxbytes { get; set; }
        public Nullable<short> examplesmode { get; set; }
        public Nullable<long> submissionstart { get; set; }
        public Nullable<long> submissionend { get; set; }
        public Nullable<long> assessmentstart { get; set; }
        public Nullable<long> assessmentend { get; set; }
        public short phaseswitchassessment { get; set; }
        public string conclusion { get; set; }
        public short conclusionformat { get; set; }
        public Nullable<short> overallfeedbackmode { get; set; }
        public Nullable<short> overallfeedbackfiles { get; set; }
        public string overallfeedbackfiletypes { get; set; }
        public Nullable<long> overallfeedbackmaxbytes { get; set; }
    }
}
