//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_contracts
    {
        public long id { get; set; }
        public Nullable<short> typeid { get; set; }
        public string num { get; set; }
        public string numpass { get; set; }
        public long date { get; set; }
        public Nullable<long> sellerid { get; set; }
        public Nullable<long> clientid { get; set; }
        public Nullable<long> studentid { get; set; }
        public long adddate { get; set; }
        public string notes { get; set; }
        public Nullable<long> departmentid { get; set; }
        public string status { get; set; }
        public string contractform { get; set; }
        public string organizationid { get; set; }
        public Nullable<long> curatorid { get; set; }
        public Nullable<long> enddate { get; set; }
        public Nullable<long> metacontractid { get; set; }
    }
}
