//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshop_assessments
    {
        public long id { get; set; }
        public long submissionid { get; set; }
        public long reviewerid { get; set; }
        public long weight { get; set; }
        public Nullable<long> timecreated { get; set; }
        public Nullable<long> timemodified { get; set; }
        public Nullable<decimal> grade { get; set; }
        public Nullable<decimal> gradinggrade { get; set; }
        public Nullable<decimal> gradinggradeover { get; set; }
        public Nullable<long> gradinggradeoverby { get; set; }
        public string feedbackauthor { get; set; }
        public Nullable<short> feedbackauthorformat { get; set; }
        public Nullable<short> feedbackauthorattachment { get; set; }
        public string feedbackreviewer { get; set; }
        public Nullable<short> feedbackreviewerformat { get; set; }
    }
}
