//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lti
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public Nullable<short> introformat { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public Nullable<long> typeid { get; set; }
        public string toolurl { get; set; }
        public string securetoolurl { get; set; }
        public Nullable<short> instructorchoicesendname { get; set; }
        public Nullable<short> instructorchoicesendemailaddr { get; set; }
        public Nullable<short> instructorchoiceallowroster { get; set; }
        public Nullable<short> instructorchoiceallowsetting { get; set; }
        public string instructorcustomparameters { get; set; }
        public Nullable<short> instructorchoiceacceptgrades { get; set; }
        public long grade { get; set; }
        public short launchcontainer { get; set; }
        public string resourcekey { get; set; }
        public string password { get; set; }
        public short debuglaunch { get; set; }
        public short showtitlelaunch { get; set; }
        public short showdescriptionlaunch { get; set; }
        public string servicesalt { get; set; }
        public string icon { get; set; }
        public string secureicon { get; set; }
    }
}
