//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_mnet_session
    {
        public long id { get; set; }
        public long userid { get; set; }
        public string username { get; set; }
        public string token { get; set; }
        public long mnethostid { get; set; }
        public string useragent { get; set; }
        public long confirm_timeout { get; set; }
        public string session_id { get; set; }
        public long expires { get; set; }
    }
}
