//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_programmitems
    {
        public long id { get; set; }
        public Nullable<long> programmid { get; set; }
        public Nullable<long> agenum { get; set; }
        public Nullable<long> courseclsid { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<long> mdlcourse { get; set; }
        public string type { get; set; }
        public string required { get; set; }
        public Nullable<int> maxcredit { get; set; }
        public Nullable<long> maxduration { get; set; }
        public Nullable<long> hours { get; set; }
        public Nullable<long> hourstheory { get; set; }
        public Nullable<long> hourspractice { get; set; }
        public Nullable<short> eduweeks { get; set; }
        public Nullable<long> instrlevelid { get; set; }
        public string gradelevel { get; set; }
        public string scale { get; set; }
        public string mingrade { get; set; }
        public string sname { get; set; }
        public string scode { get; set; }
        public string status { get; set; }
        public Nullable<long> departmentid { get; set; }
        public string about { get; set; }
        public string notice { get; set; }
        public Nullable<long> controltypeid { get; set; }
        public Nullable<long> hoursweek { get; set; }
        public string explanatory { get; set; }
        public Nullable<short> gradesyncenabled { get; set; }
        public Nullable<short> incjournwithoutgrade { get; set; }
        public Nullable<short> incjournwithunsatisfgrade { get; set; }
        public Nullable<long> altgradeitem { get; set; }
        public string metasyncon { get; set; }
        public Nullable<long> metaprogrammitemid { get; set; }
        public string billingtext { get; set; }
        public string billingrules { get; set; }
        public double salfactor { get; set; }
        public Nullable<long> hourslab { get; set; }
        public Nullable<long> hoursind { get; set; }
        public Nullable<long> hourscontrol { get; set; }
        public short autohours { get; set; }
        public Nullable<long> hoursclassroom { get; set; }
    }
}
