//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_persons
    {
        public long id { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string sortname { get; set; }
        public string preferredname { get; set; }
        public Nullable<long> dateofbirth { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string phonehome { get; set; }
        public string phonework { get; set; }
        public string phonecell { get; set; }
        public Nullable<short> passtypeid { get; set; }
        public string passportserial { get; set; }
        public string passportnum { get; set; }
        public Nullable<long> passportdate { get; set; }
        public string passportem { get; set; }
        public string citizenship { get; set; }
        public Nullable<long> passportaddrid { get; set; }
        public Nullable<long> mdluser { get; set; }
        public string sync2moodle { get; set; }
        public Nullable<long> addressid { get; set; }
        public string status { get; set; }
        public Nullable<long> adddate { get; set; }
        public Nullable<long> birthaddressid { get; set; }
        public Nullable<long> departmentid { get; set; }
        public string about { get; set; }
        public string skype { get; set; }
        public string phoneadd1 { get; set; }
        public string phoneadd2 { get; set; }
        public string phoneadd3 { get; set; }
        public string emailadd1 { get; set; }
        public string emailadd2 { get; set; }
        public string emailadd3 { get; set; }
    }
}
