//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_event
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public short format { get; set; }
        public long courseid { get; set; }
        public long groupid { get; set; }
        public long userid { get; set; }
        public long repeatid { get; set; }
        public string modulename { get; set; }
        public long instance { get; set; }
        public string eventtype { get; set; }
        public long timestart { get; set; }
        public long timeduration { get; set; }
        public short visible { get; set; }
        public string uuid { get; set; }
        public long sequence { get; set; }
        public long timemodified { get; set; }
        public Nullable<long> subscriptionid { get; set; }
    }
}
