//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_grade_outcomes
    {
        public long id { get; set; }
        public Nullable<long> courseid { get; set; }
        public string shortname { get; set; }
        public string fullname { get; set; }
        public Nullable<long> scaleid { get; set; }
        public string description { get; set; }
        public short descriptionformat { get; set; }
        public Nullable<long> timecreated { get; set; }
        public Nullable<long> timemodified { get; set; }
        public Nullable<long> usermodified { get; set; }
    }
}
