//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_seq_objective
    {
        public long id { get; set; }
        public long scoid { get; set; }
        public short primaryobj { get; set; }
        public string objectiveid { get; set; }
        public short satisfiedbymeasure { get; set; }
        public double minnormalizedmeasure { get; set; }
    }
}
