//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_event_subscriptions
    {
        public long id { get; set; }
        public string url { get; set; }
        public long courseid { get; set; }
        public long groupid { get; set; }
        public long userid { get; set; }
        public string eventtype { get; set; }
        public long pollinterval { get; set; }
        public Nullable<long> lastupdated { get; set; }
        public string name { get; set; }
    }
}
