//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_quiz_overview_regrades
    {
        public long id { get; set; }
        public long questionusageid { get; set; }
        public long slot { get; set; }
        public Nullable<decimal> newfraction { get; set; }
        public Nullable<decimal> oldfraction { get; set; }
        public short regraded { get; set; }
        public long timemodified { get; set; }
    }
}
