//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshopallocation_scheduled
    {
        public long id { get; set; }
        public long workshopid { get; set; }
        public short enabled { get; set; }
        public long submissionend { get; set; }
        public Nullable<long> timeallocated { get; set; }
        public string settings { get; set; }
        public Nullable<long> resultstatus { get; set; }
        public string resultmessage { get; set; }
        public string resultlog { get; set; }
    }
}
