//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_user_devices
    {
        public long id { get; set; }
        public long userid { get; set; }
        public string appid { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public string platform { get; set; }
        public string version { get; set; }
        public string pushid { get; set; }
        public string uuid { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
