//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_addresses
    {
        public long id { get; set; }
        public Nullable<short> type { get; set; }
        public string postalcode { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string county { get; set; }
        public string city { get; set; }
        public string streetname { get; set; }
        public string streettype { get; set; }
        public string number { get; set; }
        public string gate { get; set; }
        public string floor { get; set; }
        public string apartment { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string status { get; set; }
    }
}
