//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_task_adhoc
    {
        public long id { get; set; }
        public string component { get; set; }
        public string classname { get; set; }
        public long nextruntime { get; set; }
        public Nullable<long> faildelay { get; set; }
        public string customdata { get; set; }
        public short blocking { get; set; }
    }
}
