//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_synclogs
    {
        public long id { get; set; }
        public long syncid { get; set; }
        public Nullable<long> executetime { get; set; }
        public string operation { get; set; }
        public string direct { get; set; }
        public string prevoperation { get; set; }
        public string error { get; set; }
        public string textlog { get; set; }
        public string optlog { get; set; }
    }
}
