//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_tool_monitor_events
    {
        public long id { get; set; }
        public string eventname { get; set; }
        public long contextid { get; set; }
        public long contextlevel { get; set; }
        public long contextinstanceid { get; set; }
        public string link { get; set; }
        public long courseid { get; set; }
        public long timecreated { get; set; }
    }
}
