//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_offlinequiz_groups
    {
        public long id { get; set; }
        public long offlinequizid { get; set; }
        public short number { get; set; }
        public decimal sumgrades { get; set; }
        public short numberofpages { get; set; }
        public long templateusageid { get; set; }
        public string questionfilename { get; set; }
        public string answerfilename { get; set; }
        public string correctionfilename { get; set; }
    }
}
