//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_reports
    {
        public long id { get; set; }
        public string plugintype { get; set; }
        public string plugincode { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<long> personid { get; set; }
        public Nullable<long> requestdate { get; set; }
        public Nullable<long> completedate { get; set; }
        public Nullable<long> crondate { get; set; }
        public string status { get; set; }
        public Nullable<long> departmentid { get; set; }
        public Nullable<long> objectid { get; set; }
        public Nullable<long> begindate { get; set; }
        public Nullable<long> enddate { get; set; }
        public string requestdata { get; set; }
        public string filepath { get; set; }
    }
}
