//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_question_attempt_steps
    {
        public long id { get; set; }
        public long questionattemptid { get; set; }
        public long sequencenumber { get; set; }
        public string state { get; set; }
        public Nullable<decimal> fraction { get; set; }
        public long timecreated { get; set; }
        public Nullable<long> userid { get; set; }
    }
}
