//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_events
    {
        public long id { get; set; }
        public string plugintype { get; set; }
        public string plugincode { get; set; }
        public string eventcode { get; set; }
        public string rplugintype { get; set; }
        public string rplugincode { get; set; }
    }
}
