//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_mnet_application
    {
        public long id { get; set; }
        public string name { get; set; }
        public string display_name { get; set; }
        public string xmlrpc_server_url { get; set; }
        public string sso_land_url { get; set; }
        public string sso_jump_url { get; set; }
    }
}
