//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_offlinequiz_group_questions
    {
        public long id { get; set; }
        public long offlinequizid { get; set; }
        public long offlinegroupid { get; set; }
        public long questionid { get; set; }
        public short position { get; set; }
        public Nullable<short> page { get; set; }
        public Nullable<short> slot { get; set; }
        public decimal maxmark { get; set; }
    }
}
