//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_schpresences
    {
        public long id { get; set; }
        public Nullable<long> eventid { get; set; }
        public Nullable<long> personid { get; set; }
        public string present { get; set; }
        public Nullable<long> orderid { get; set; }
        public Nullable<long> mdlevent { get; set; }
    }
}
