//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_seq_rolluprule
    {
        public long id { get; set; }
        public long scoid { get; set; }
        public string childactivityset { get; set; }
        public long minimumcount { get; set; }
        public double minimumpercent { get; set; }
        public string conditioncombination { get; set; }
        public string action { get; set; }
    }
}
