//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_glossary_formats
    {
        public long id { get; set; }
        public string name { get; set; }
        public string popupformatname { get; set; }
        public short visible { get; set; }
        public short showgroup { get; set; }
        public string showtabs { get; set; }
        public string defaultmode { get; set; }
        public string defaulthook { get; set; }
        public string sortkey { get; set; }
        public string sortorder { get; set; }
    }
}
