//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_aicc_session
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long scormid { get; set; }
        public string hacpsession { get; set; }
        public Nullable<long> scoid { get; set; }
        public string scormmode { get; set; }
        public string scormstatus { get; set; }
        public Nullable<long> attempt { get; set; }
        public string lessonstatus { get; set; }
        public string sessiontime { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
