//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_quiz_feedback
    {
        public long id { get; set; }
        public long quizid { get; set; }
        public string feedbacktext { get; set; }
        public short feedbacktextformat { get; set; }
        public decimal mingrade { get; set; }
        public decimal maxgrade { get; set; }
    }
}
