//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_user_private_key
    {
        public long id { get; set; }
        public string script { get; set; }
        public string value { get; set; }
        public long userid { get; set; }
        public Nullable<long> instance { get; set; }
        public string iprestriction { get; set; }
        public Nullable<long> validuntil { get; set; }
        public Nullable<long> timecreated { get; set; }
    }
}
