//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_course_sections
    {
        public long id { get; set; }
        public long course { get; set; }
        public long section { get; set; }
        public string name { get; set; }
        public string summary { get; set; }
        public short summaryformat { get; set; }
        public string sequence { get; set; }
        public short visible { get; set; }
        public string availability { get; set; }
    }
}
