//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_offlinequiz_page_corners
    {
        public long id { get; set; }
        public long scannedpageid { get; set; }
        public short x { get; set; }
        public short y { get; set; }
        public short position { get; set; }
    }
}
