//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_statushistory
    {
        public long id { get; set; }
        public string status { get; set; }
        public string prevstatus { get; set; }
        public string plugintype { get; set; }
        public string plugincode { get; set; }
        public Nullable<long> muserid { get; set; }
        public Nullable<long> objectid { get; set; }
        public Nullable<long> statusdate { get; set; }
        public string notes { get; set; }
        public string opt { get; set; }
        public Nullable<long> orderid { get; set; }
    }
}
