//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lesson_answers
    {
        public long id { get; set; }
        public long lessonid { get; set; }
        public long pageid { get; set; }
        public long jumpto { get; set; }
        public short grade { get; set; }
        public long score { get; set; }
        public short flags { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string answer { get; set; }
        public short answerformat { get; set; }
        public string response { get; set; }
        public short responseformat { get; set; }
    }
}
