//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_tool_monitor_rules
    {
        public long id { get; set; }
        public string description { get; set; }
        public short descriptionformat { get; set; }
        public string name { get; set; }
        public long userid { get; set; }
        public long courseid { get; set; }
        public string plugin { get; set; }
        public string eventname { get; set; }
        public string template { get; set; }
        public short templateformat { get; set; }
        public short frequency { get; set; }
        public int timewindow { get; set; }
        public long timemodified { get; set; }
        public long timecreated { get; set; }
    }
}
