//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_editor_atto_autosave
    {
        public long id { get; set; }
        public string elementid { get; set; }
        public long contextid { get; set; }
        public string pagehash { get; set; }
        public long userid { get; set; }
        public string drafttext { get; set; }
        public Nullable<long> draftid { get; set; }
        public string pageinstance { get; set; }
        public long timemodified { get; set; }
    }
}
