//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_tag_instance
    {
        public long id { get; set; }
        public long tagid { get; set; }
        public string component { get; set; }
        public string itemtype { get; set; }
        public long itemid { get; set; }
        public Nullable<long> contextid { get; set; }
        public long tiuserid { get; set; }
        public Nullable<long> ordering { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
