//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_course_modules
    {
        public long id { get; set; }
        public long course { get; set; }
        public long module { get; set; }
        public long instance { get; set; }
        public long section { get; set; }
        public string idnumber { get; set; }
        public long added { get; set; }
        public short score { get; set; }
        public int indent { get; set; }
        public short visible { get; set; }
        public short visibleold { get; set; }
        public short groupmode { get; set; }
        public long groupingid { get; set; }
        public short completion { get; set; }
        public Nullable<long> completiongradeitemnumber { get; set; }
        public short completionview { get; set; }
        public long completionexpected { get; set; }
        public short showdescription { get; set; }
        public string availability { get; set; }
    }
}
