//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_grading_instances
    {
        public long id { get; set; }
        public long definitionid { get; set; }
        public long raterid { get; set; }
        public Nullable<long> itemid { get; set; }
        public Nullable<decimal> rawgrade { get; set; }
        public long status { get; set; }
        public string feedback { get; set; }
        public Nullable<short> feedbackformat { get; set; }
        public long timemodified { get; set; }
    }
}
