//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshop_grades
    {
        public long id { get; set; }
        public long assessmentid { get; set; }
        public string strategy { get; set; }
        public long dimensionid { get; set; }
        public decimal grade { get; set; }
        public string peercomment { get; set; }
        public Nullable<short> peercommentformat { get; set; }
    }
}
