//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_files
    {
        public long id { get; set; }
        public string contenthash { get; set; }
        public string pathnamehash { get; set; }
        public long contextid { get; set; }
        public string component { get; set; }
        public string filearea { get; set; }
        public long itemid { get; set; }
        public string filepath { get; set; }
        public string filename { get; set; }
        public Nullable<long> userid { get; set; }
        public long filesize { get; set; }
        public string mimetype { get; set; }
        public long status { get; set; }
        public string source { get; set; }
        public string author { get; set; }
        public string license { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long sortorder { get; set; }
        public Nullable<long> referencefileid { get; set; }
    }
}
