//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_qtype_match_subquestions
    {
        public long id { get; set; }
        public long questionid { get; set; }
        public string questiontext { get; set; }
        public short questiontextformat { get; set; }
        public string answertext { get; set; }
    }
}
