//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_survey_questions
    {
        public long id { get; set; }
        public string text { get; set; }
        public string shorttext { get; set; }
        public string multi { get; set; }
        public string intro { get; set; }
        public short type { get; set; }
        public string options { get; set; }
    }
}
