//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_log_display
    {
        public long id { get; set; }
        public string module { get; set; }
        public string action { get; set; }
        public string mtable { get; set; }
        public string field { get; set; }
        public string component { get; set; }
    }
}
