//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_plans
    {
        public long id { get; set; }
        public Nullable<long> linkid { get; set; }
        public string linktype { get; set; }
        public Nullable<long> parentid { get; set; }
        public string name { get; set; }
        public Nullable<long> date { get; set; }
        public Nullable<long> reldate { get; set; }
        public Nullable<long> reldldate { get; set; }
        public string scale { get; set; }
        public string type { get; set; }
        public string typesync { get; set; }
        public Nullable<long> mdlinstance { get; set; }
        public string status { get; set; }
        public string homework { get; set; }
        public Nullable<long> homeworkhours { get; set; }
        public Nullable<short> directmap { get; set; }
        public Nullable<long> number { get; set; }
        public Nullable<long> datetheme { get; set; }
        public Nullable<long> plansectionsid { get; set; }
        public string note { get; set; }
    }
}
