//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_orders
    {
        public long id { get; set; }
        public string plugintype { get; set; }
        public string plugincode { get; set; }
        public string pluginversion { get; set; }
        public string code { get; set; }
        public string num { get; set; }
        public Nullable<long> departmentid { get; set; }
        public Nullable<long> ownerid { get; set; }
        public Nullable<long> signerid { get; set; }
        public Nullable<long> date { get; set; }
        public Nullable<long> signdate { get; set; }
        public Nullable<long> exdate { get; set; }
        public Nullable<long> crondate { get; set; }
        public Nullable<long> changedate { get; set; }
        public string status { get; set; }
        public string sdata { get; set; }
        public string signature { get; set; }
        public string notes { get; set; }
    }
}
