//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_wiki_pages
    {
        public long id { get; set; }
        public long subwikiid { get; set; }
        public string title { get; set; }
        public string cachedcontent { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long timerendered { get; set; }
        public long userid { get; set; }
        public long pageviews { get; set; }
        public short @readonly { get; set; }
    }
}
