//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lti_types
    {
        public long id { get; set; }
        public string name { get; set; }
        public string baseurl { get; set; }
        public string tooldomain { get; set; }
        public short state { get; set; }
        public long course { get; set; }
        public short coursevisible { get; set; }
        public Nullable<long> toolproxyid { get; set; }
        public string enabledcapability { get; set; }
        public string parameter { get; set; }
        public string icon { get; set; }
        public string secureicon { get; set; }
        public long createdby { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string description { get; set; }
    }
}
