//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_tool_customlang
    {
        public long id { get; set; }
        public string lang { get; set; }
        public long componentid { get; set; }
        public string stringid { get; set; }
        public string original { get; set; }
        public string master { get; set; }
        public string local { get; set; }
        public long timemodified { get; set; }
        public Nullable<long> timecustomized { get; set; }
        public Nullable<short> outdated { get; set; }
        public Nullable<short> modified { get; set; }
    }
}
