//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_wiziq
    {
        public long id { get; set; }
        public long course { get; set; }
        public Nullable<long> insescod { get; set; }
        public Nullable<long> class_id { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public long wiziq_datetime { get; set; }
        public string class_timezone { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long duration { get; set; }
        public string vc_language { get; set; }
        public Nullable<long> recording { get; set; }
        public long presenter_id { get; set; }
        public Nullable<long> lasteditorid { get; set; }
        public string class_status { get; set; }
        public string recording_link { get; set; }
        public string view_recording_link { get; set; }
        public Nullable<long> recording_link_status { get; set; }
    }
}
