//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshop_assessments_old
    {
        public long id { get; set; }
        public long workshopid { get; set; }
        public long submissionid { get; set; }
        public long userid { get; set; }
        public long timecreated { get; set; }
        public long timegraded { get; set; }
        public long timeagreed { get; set; }
        public double grade { get; set; }
        public short gradinggrade { get; set; }
        public short teachergraded { get; set; }
        public short mailed { get; set; }
        public short resubmission { get; set; }
        public short donotuse { get; set; }
        public string generalcomment { get; set; }
        public string teachercomment { get; set; }
        public string newplugin { get; set; }
        public Nullable<long> newid { get; set; }
    }
}
