//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_repository_instances
    {
        public long id { get; set; }
        public string name { get; set; }
        public long typeid { get; set; }
        public long userid { get; set; }
        public long contextid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<long> timecreated { get; set; }
        public Nullable<long> timemodified { get; set; }
        public short @readonly { get; set; }
    }
}
