//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_task_scheduled
    {
        public long id { get; set; }
        public string component { get; set; }
        public string classname { get; set; }
        public Nullable<long> lastruntime { get; set; }
        public Nullable<long> nextruntime { get; set; }
        public short blocking { get; set; }
        public string minute { get; set; }
        public string hour { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string dayofweek { get; set; }
        public Nullable<long> faildelay { get; set; }
        public short customised { get; set; }
        public short disabled { get; set; }
    }
}
