//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_assignment_submissions
    {
        public long id { get; set; }
        public long assignment { get; set; }
        public long userid { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public long numfiles { get; set; }
        public string data1 { get; set; }
        public string data2 { get; set; }
        public long grade { get; set; }
        public string submissioncomment { get; set; }
        public short format { get; set; }
        public long teacher { get; set; }
        public long timemarked { get; set; }
        public short mailed { get; set; }
    }
}
