//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_workplaces
    {
        public long id { get; set; }
        public Nullable<long> personid { get; set; }
        public Nullable<long> organizationid { get; set; }
        public string statuswork { get; set; }
        public string post { get; set; }
        public Nullable<long> receptiondate { get; set; }
        public Nullable<long> dismissaldate { get; set; }
        public string phonework { get; set; }
        public string addnumber { get; set; }
        public string comment { get; set; }
    }
}
