//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_portfolio_log
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long time { get; set; }
        public long portfolio { get; set; }
        public string caller_class { get; set; }
        public string caller_file { get; set; }
        public string caller_component { get; set; }
        public string caller_sha1 { get; set; }
        public long tempdataid { get; set; }
        public string returnurl { get; set; }
        public string continueurl { get; set; }
    }
}
