//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_assignsubmission_onlinetext
    {
        public long id { get; set; }
        public long assignment { get; set; }
        public long submission { get; set; }
        public string onlinetext { get; set; }
        public short onlineformat { get; set; }
    }
}
