//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_cpassed
    {
        public long id { get; set; }
        public Nullable<long> cstreamid { get; set; }
        public Nullable<long> programmsbcid { get; set; }
        public Nullable<long> programmitemid { get; set; }
        public Nullable<long> studentid { get; set; }
        public Nullable<long> agroupid { get; set; }
        public string grade { get; set; }
        public string gradelevel { get; set; }
        public Nullable<int> credit { get; set; }
        public string notice { get; set; }
        public Nullable<long> repeatid { get; set; }
        public Nullable<short> typesync { get; set; }
        public Nullable<long> mdlinstance { get; set; }
        public Nullable<long> teacherid { get; set; }
        public Nullable<long> ageid { get; set; }
        public Nullable<long> orderid { get; set; }
        public string status { get; set; }
        public Nullable<long> begindate { get; set; }
        public Nullable<long> enddate { get; set; }
        public Nullable<long> sbcorderid { get; set; }
        public Nullable<long> learninghistoryid { get; set; }
    }
}
