//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_agrouphistory
    {
        public long id { get; set; }
        public long agroupid { get; set; }
        public long ageid { get; set; }
        public long agenum { get; set; }
        public long changedate { get; set; }
        public Nullable<long> orderid { get; set; }
    }
}
