//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_tag_coll
    {
        public long id { get; set; }
        public string name { get; set; }
        public short isdefault { get; set; }
        public string component { get; set; }
        public int sortorder { get; set; }
        public short searchable { get; set; }
        public string customurl { get; set; }
    }
}
