//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_blog_external
    {
        public long id { get; set; }
        public long userid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string filtertags { get; set; }
        public short failedlastsync { get; set; }
        public Nullable<long> timemodified { get; set; }
        public long timefetched { get; set; }
    }
}
