//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_bigbluebuttonbn
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public short introformat { get; set; }
        public string meetingid { get; set; }
        public string moderatorpass { get; set; }
        public string viewerpass { get; set; }
        public short newwindow { get; set; }
        public short wait { get; set; }
        public short record { get; set; }
        public short tagging { get; set; }
        public string welcome { get; set; }
        public int voicebridge { get; set; }
        public long openingtime { get; set; }
        public long closingtime { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string presentation { get; set; }
        public string participants { get; set; }
        public short userlimit { get; set; }
    }
}
