//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_wiki_links
    {
        public long id { get; set; }
        public long subwikiid { get; set; }
        public long frompageid { get; set; }
        public long topageid { get; set; }
        public string tomissingpage { get; set; }
    }
}
