//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_enrol_lti_tools
    {
        public long id { get; set; }
        public long enrolid { get; set; }
        public long contextid { get; set; }
        public string institution { get; set; }
        public string lang { get; set; }
        public string timezone { get; set; }
        public long maxenrolled { get; set; }
        public short maildisplay { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public short gradesync { get; set; }
        public short gradesynccompletion { get; set; }
        public short membersync { get; set; }
        public short membersyncmode { get; set; }
        public long roleinstructor { get; set; }
        public long rolelearner { get; set; }
        public string secret { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
