//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lti_submission
    {
        public long id { get; set; }
        public long ltiid { get; set; }
        public long userid { get; set; }
        public long datesubmitted { get; set; }
        public long dateupdated { get; set; }
        public decimal gradepercent { get; set; }
        public decimal originalgrade { get; set; }
        public long launchid { get; set; }
        public short state { get; set; }
    }
}
