//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lock_db
    {
        public long id { get; set; }
        public string resourcekey { get; set; }
        public Nullable<long> expires { get; set; }
        public string owner { get; set; }
    }
}
