//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshop_submissions
    {
        public long id { get; set; }
        public long workshopid { get; set; }
        public Nullable<short> example { get; set; }
        public long authorid { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public short contentformat { get; set; }
        public short contenttrust { get; set; }
        public Nullable<short> attachment { get; set; }
        public Nullable<decimal> grade { get; set; }
        public Nullable<decimal> gradeover { get; set; }
        public Nullable<long> gradeoverby { get; set; }
        public string feedbackauthor { get; set; }
        public Nullable<short> feedbackauthorformat { get; set; }
        public Nullable<long> timegraded { get; set; }
        public Nullable<short> published { get; set; }
        public short late { get; set; }
    }
}
