//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_question_categories
    {
        public long id { get; set; }
        public string name { get; set; }
        public long contextid { get; set; }
        public string info { get; set; }
        public short infoformat { get; set; }
        public string stamp { get; set; }
        public long parent { get; set; }
        public long sortorder { get; set; }
    }
}
