//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_assignfeedback_comments
    {
        public long id { get; set; }
        public long assignment { get; set; }
        public long grade { get; set; }
        public string commenttext { get; set; }
        public short commentformat { get; set; }
    }
}
