//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_backup_controllers
    {
        public long id { get; set; }
        public string backupid { get; set; }
        public string operation { get; set; }
        public string type { get; set; }
        public long itemid { get; set; }
        public string format { get; set; }
        public short interactive { get; set; }
        public short purpose { get; set; }
        public long userid { get; set; }
        public short status { get; set; }
        public short execution { get; set; }
        public long executiontime { get; set; }
        public string checksum { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public string controller { get; set; }
    }
}
