//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_enrol
    {
        public long id { get; set; }
        public string enrol { get; set; }
        public long status { get; set; }
        public long courseid { get; set; }
        public long sortorder { get; set; }
        public string name { get; set; }
        public Nullable<long> enrolperiod { get; set; }
        public Nullable<long> enrolstartdate { get; set; }
        public Nullable<long> enrolenddate { get; set; }
        public Nullable<short> expirynotify { get; set; }
        public Nullable<long> expirythreshold { get; set; }
        public Nullable<short> notifyall { get; set; }
        public string password { get; set; }
        public string cost { get; set; }
        public string currency { get; set; }
        public Nullable<long> roleid { get; set; }
        public Nullable<long> customint1 { get; set; }
        public Nullable<long> customint2 { get; set; }
        public Nullable<long> customint3 { get; set; }
        public Nullable<long> customint4 { get; set; }
        public Nullable<long> customint5 { get; set; }
        public Nullable<long> customint6 { get; set; }
        public Nullable<long> customint7 { get; set; }
        public Nullable<long> customint8 { get; set; }
        public string customchar1 { get; set; }
        public string customchar2 { get; set; }
        public string customchar3 { get; set; }
        public Nullable<decimal> customdec1 { get; set; }
        public Nullable<decimal> customdec2 { get; set; }
        public string customtext1 { get; set; }
        public string customtext2 { get; set; }
        public string customtext3 { get; set; }
        public string customtext4 { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
    }
}
