//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_mnet_sso_access_control
    {
        public long id { get; set; }
        public string username { get; set; }
        public long mnet_host_id { get; set; }
        public string accessctrl { get; set; }
    }
}
