//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_schevents
    {
        public long id { get; set; }
        public Nullable<long> templateid { get; set; }
        public Nullable<long> dayid { get; set; }
        public Nullable<long> planid { get; set; }
        public string type { get; set; }
        public long joinid { get; set; }
        public Nullable<long> cstreamid { get; set; }
        public Nullable<long> teacherid { get; set; }
        public Nullable<long> date { get; set; }
        public Nullable<long> duration { get; set; }
        public string place { get; set; }
        public Nullable<long> replaceid { get; set; }
        public string status { get; set; }
        public string form { get; set; }
        public Nullable<long> appointmentid { get; set; }
        public Nullable<long> ahours { get; set; }
        public double salfactor { get; set; }
        public string salfactorparts { get; set; }
        public Nullable<double> rhours { get; set; }
    }
}
