//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_aclwarrantagents
    {
        public long id { get; set; }
        public long departmentid { get; set; }
        public Nullable<long> personid { get; set; }
        public string baseptype { get; set; }
        public string basepcode { get; set; }
        public string basetype { get; set; }
        public long baseid { get; set; }
        public long aclwarrantid { get; set; }
        public long datecreate { get; set; }
        public long begindate { get; set; }
        public long duration { get; set; }
        public string status { get; set; }
        public short isdelegatable { get; set; }
    }
}
