//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_profiling
    {
        public long id { get; set; }
        public string runid { get; set; }
        public string url { get; set; }
        public string data { get; set; }
        public long totalexecutiontime { get; set; }
        public long totalcputime { get; set; }
        public long totalcalls { get; set; }
        public long totalmemory { get; set; }
        public short runreference { get; set; }
        public string runcomment { get; set; }
        public long timecreated { get; set; }
    }
}
