//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_enrol_lti_users
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long toolid { get; set; }
        public string serviceurl { get; set; }
        public string sourceid { get; set; }
        public string consumerkey { get; set; }
        public string consumersecret { get; set; }
        public string membershipsurl { get; set; }
        public string membershipsid { get; set; }
        public Nullable<decimal> lastgrade { get; set; }
        public Nullable<long> lastaccess { get; set; }
        public Nullable<long> timecreated { get; set; }
    }
}
