//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_comments
    {
        public long id { get; set; }
        public long contextid { get; set; }
        public string component { get; set; }
        public string commentarea { get; set; }
        public long itemid { get; set; }
        public string content { get; set; }
        public short format { get; set; }
        public long userid { get; set; }
        public long timecreated { get; set; }
    }
}
