//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_external_functions
    {
        public long id { get; set; }
        public string name { get; set; }
        public string classname { get; set; }
        public string methodname { get; set; }
        public string classpath { get; set; }
        public string component { get; set; }
        public string capabilities { get; set; }
        public string services { get; set; }
    }
}
