//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_plugins
    {
        public long id { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string version { get; set; }
        public Nullable<long> cron { get; set; }
        public Nullable<long> lastcron { get; set; }
    }
}
