//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_quiz_overrides
    {
        public long id { get; set; }
        public long quiz { get; set; }
        public Nullable<long> groupid { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<long> timeopen { get; set; }
        public Nullable<long> timeclose { get; set; }
        public Nullable<long> timelimit { get; set; }
        public Nullable<int> attempts { get; set; }
        public string password { get; set; }
    }
}
