//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_feedback_valuetmp
    {
        public long id { get; set; }
        public long course_id { get; set; }
        public long item { get; set; }
        public long completed { get; set; }
        public long tmp_completed { get; set; }
        public string value { get; set; }
    }
}
