//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_appointments
    {
        public long id { get; set; }
        public Nullable<long> eagreementid { get; set; }
        public Nullable<long> schpositionid { get; set; }
        public string enumber { get; set; }
        public Nullable<decimal> worktime { get; set; }
        public Nullable<long> date { get; set; }
        public Nullable<long> begindate { get; set; }
        public Nullable<long> enddate { get; set; }
        public Nullable<long> departmentid { get; set; }
        public string status { get; set; }
        public Nullable<short> combination { get; set; }
    }
}
