//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_seq_mapinfo
    {
        public long id { get; set; }
        public long scoid { get; set; }
        public long objectiveid { get; set; }
        public long targetobjectiveid { get; set; }
        public short readsatisfiedstatus { get; set; }
        public short readnormalizedmeasure { get; set; }
        public short writesatisfiedstatus { get; set; }
        public short writenormalizedmeasure { get; set; }
    }
}
