//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_format_grid_icon
    {
        public long id { get; set; }
        public string image { get; set; }
        public long displayedimageindex { get; set; }
        public long sectionid { get; set; }
        public long courseid { get; set; }
    }
}
