//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_course_completion_criteria
    {
        public long id { get; set; }
        public long course { get; set; }
        public long criteriatype { get; set; }
        public string module { get; set; }
        public Nullable<long> moduleinstance { get; set; }
        public Nullable<long> courseinstance { get; set; }
        public Nullable<long> enrolperiod { get; set; }
        public Nullable<long> timeend { get; set; }
        public Nullable<decimal> gradepass { get; set; }
        public Nullable<long> role { get; set; }
    }
}
