//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_course_request
    {
        public long id { get; set; }
        public string fullname { get; set; }
        public string shortname { get; set; }
        public string summary { get; set; }
        public short summaryformat { get; set; }
        public long category { get; set; }
        public string reason { get; set; }
        public long requester { get; set; }
        public string password { get; set; }
    }
}
