//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_checklist_item
    {
        public long id { get; set; }
        public long checklist { get; set; }
        public long userid { get; set; }
        public string displaytext { get; set; }
        public long position { get; set; }
        public int indent { get; set; }
        public short itemoptional { get; set; }
        public Nullable<long> duetime { get; set; }
        public Nullable<long> eventid { get; set; }
        public string colour { get; set; }
        public Nullable<long> moduleid { get; set; }
        public short hidden { get; set; }
        public Nullable<long> grouping { get; set; }
    }
}
