//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_config
    {
        public long id { get; set; }
        public long departmentid { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public string value { get; set; }
        public string plugintype { get; set; }
        public string plugincode { get; set; }
        public short noextend { get; set; }
        public Nullable<long> personid { get; set; }
    }
}
