//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_scorm_scoes
    {
        public long id { get; set; }
        public long scorm { get; set; }
        public string manifest { get; set; }
        public string organization { get; set; }
        public string parent { get; set; }
        public string identifier { get; set; }
        public string launch { get; set; }
        public string scormtype { get; set; }
        public string title { get; set; }
        public long sortorder { get; set; }
    }
}
