//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_qtype_ddmarker_drops
    {
        public long id { get; set; }
        public long questionid { get; set; }
        public long no { get; set; }
        public string shape { get; set; }
        public string coords { get; set; }
        public long choice { get; set; }
    }
}
