//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_rss_client
    {
        public long id { get; set; }
        public long userid { get; set; }
        public string title { get; set; }
        public string preferredtitle { get; set; }
        public string description { get; set; }
        public short shared { get; set; }
        public string url { get; set; }
        public long skiptime { get; set; }
        public long skipuntil { get; set; }
    }
}
