//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_otcourselogic
    {
        public long id { get; set; }
        public long course { get; set; }
        public string name { get; set; }
        public string activecond { get; set; }
        public Nullable<long> checkperiod { get; set; }
        public short catchstatechange { get; set; }
        public short catchcourseviewed { get; set; }
        public short studentshide { get; set; }
        public string redirectmessage { get; set; }
        public string redirecturl { get; set; }
        public string deliveryoptions { get; set; }
        public Nullable<long> deliveryperiod { get; set; }
        public long timecreated { get; set; }
        public long timemodified { get; set; }
        public Nullable<short> completionstate { get; set; }
    }
}
