//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_orderdata
    {
        public long id { get; set; }
        public long orderid { get; set; }
        public string firstlvlname { get; set; }
        public long varnum { get; set; }
        public short scalar { get; set; }
        public string data { get; set; }
        public string ind { get; set; }
    }
}
