//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_workshopform_accumulative
    {
        public long id { get; set; }
        public long workshopid { get; set; }
        public Nullable<long> sort { get; set; }
        public string description { get; set; }
        public Nullable<short> descriptionformat { get; set; }
        public long grade { get; set; }
        public Nullable<int> weight { get; set; }
    }
}
