//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_block_dof_s_cstreams
    {
        public long id { get; set; }
        public Nullable<long> ageid { get; set; }
        public Nullable<long> programmitemid { get; set; }
        public Nullable<long> teacherid { get; set; }
        public Nullable<long> departmentid { get; set; }
        public Nullable<long> appointmentid { get; set; }
        public Nullable<long> mdlgroup { get; set; }
        public Nullable<short> eduweeks { get; set; }
        public Nullable<long> begindate { get; set; }
        public Nullable<long> enddate { get; set; }
        public string status { get; set; }
        public Nullable<long> hours { get; set; }
        public Nullable<long> hoursweek { get; set; }
        public Nullable<decimal> hoursweekinternally { get; set; }
        public string name { get; set; }
        public Nullable<decimal> hoursweekdistance { get; set; }
        public string explanatory { get; set; }
        public Nullable<long> lastgradesync { get; set; }
        public double salfactor { get; set; }
        public double substsalfactor { get; set; }
    }
}
