//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_logstore_standard_log
    {
        public long id { get; set; }
        public string eventname { get; set; }
        public string component { get; set; }
        public string action { get; set; }
        public string target { get; set; }
        public string objecttable { get; set; }
        public Nullable<long> objectid { get; set; }
        public string crud { get; set; }
        public short edulevel { get; set; }
        public long contextid { get; set; }
        public long contextlevel { get; set; }
        public long contextinstanceid { get; set; }
        public long userid { get; set; }
        public Nullable<long> courseid { get; set; }
        public Nullable<long> relateduserid { get; set; }
        public short anonymous { get; set; }
        public string other { get; set; }
        public long timecreated { get; set; }
        public string origin { get; set; }
        public string ip { get; set; }
        public Nullable<long> realuserid { get; set; }
    }
}
