//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_plagiarism_apru_files
    {
        public long id { get; set; }
        public long cm { get; set; }
        public long userid { get; set; }
        public string identifier { get; set; }
        public string externalid { get; set; }
        public string externalstatus { get; set; }
        public string statuscode { get; set; }
        public Nullable<int> similarityscore { get; set; }
        public int attempt { get; set; }
        public string filename { get; set; }
        public string contenthash { get; set; }
        public Nullable<long> lastmodified { get; set; }
        public string submissiontype { get; set; }
        public Nullable<long> parentid { get; set; }
        public Nullable<long> errorcode { get; set; }
        public string errormsg { get; set; }
        public string reporturl { get; set; }
        public string additional { get; set; }
    }
}
