//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moodle3KL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_lesson_branch
    {
        public long id { get; set; }
        public long lessonid { get; set; }
        public long userid { get; set; }
        public long pageid { get; set; }
        public long retry { get; set; }
        public short flag { get; set; }
        public long timeseen { get; set; }
        public long nextpageid { get; set; }
    }
}
