using System.Data.Common;
using System.Data.Entity;

using Moodle3KL.Domain;
using MySql.Data.Entity;

namespace Moodle3KL.Data.Infrastructure
{
    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public class Moodle3KLDbContext : DbContext
    {
        public Moodle3KLDbContext() : base(AppConfig.MoodleDecanatConnectionString)
        {
        }

        public virtual DbSet<mdl_assign> mdl_assign { get; set; }
        public virtual DbSet<mdl_assign_grades> mdl_assign_grades { get; set; }
        public virtual DbSet<mdl_assign_plugin_config> mdl_assign_plugin_config { get; set; }
        public virtual DbSet<mdl_assign_submission> mdl_assign_submission { get; set; }
        public virtual DbSet<mdl_assign_user_flags> mdl_assign_user_flags { get; set; }
        public virtual DbSet<mdl_assign_user_mapping> mdl_assign_user_mapping { get; set; }
        public virtual DbSet<mdl_assignfeedback_comments> mdl_assignfeedback_comments { get; set; }
        public virtual DbSet<mdl_assignfeedback_editpdf_annot> mdl_assignfeedback_editpdf_annot { get; set; }
        public virtual DbSet<mdl_assignfeedback_editpdf_cmnt> mdl_assignfeedback_editpdf_cmnt { get; set; }
        public virtual DbSet<mdl_assignfeedback_editpdf_queue> mdl_assignfeedback_editpdf_queue { get; set; }
        public virtual DbSet<mdl_assignfeedback_editpdf_quick> mdl_assignfeedback_editpdf_quick { get; set; }
        public virtual DbSet<mdl_assignfeedback_file> mdl_assignfeedback_file { get; set; }
        public virtual DbSet<mdl_assignment> mdl_assignment { get; set; }
        public virtual DbSet<mdl_assignment_submissions> mdl_assignment_submissions { get; set; }
        public virtual DbSet<mdl_assignment_upgrade> mdl_assignment_upgrade { get; set; }
        public virtual DbSet<mdl_assignsubmission_file> mdl_assignsubmission_file { get; set; }
        public virtual DbSet<mdl_assignsubmission_onlinetext> mdl_assignsubmission_onlinetext { get; set; }
        public virtual DbSet<mdl_auth_otoauth> mdl_auth_otoauth { get; set; }
        public virtual DbSet<mdl_availability_password_grant> mdl_availability_password_grant { get; set; }
        public virtual DbSet<mdl_backup_controllers> mdl_backup_controllers { get; set; }
        public virtual DbSet<mdl_backup_courses> mdl_backup_courses { get; set; }
        public virtual DbSet<mdl_backup_logs> mdl_backup_logs { get; set; }
        public virtual DbSet<mdl_badge> mdl_badge { get; set; }
        public virtual DbSet<mdl_badge_backpack> mdl_badge_backpack { get; set; }
        public virtual DbSet<mdl_badge_criteria> mdl_badge_criteria { get; set; }
        public virtual DbSet<mdl_badge_criteria_met> mdl_badge_criteria_met { get; set; }
        public virtual DbSet<mdl_badge_criteria_param> mdl_badge_criteria_param { get; set; }
        public virtual DbSet<mdl_badge_external> mdl_badge_external { get; set; }
        public virtual DbSet<mdl_badge_issued> mdl_badge_issued { get; set; }
        public virtual DbSet<mdl_badge_manual_award> mdl_badge_manual_award { get; set; }
        public virtual DbSet<mdl_bigbluebuttonbn> mdl_bigbluebuttonbn { get; set; }
        public virtual DbSet<mdl_bigbluebuttonbn_logs> mdl_bigbluebuttonbn_logs { get; set; }
        public virtual DbSet<mdl_block> mdl_block { get; set; }
        public virtual DbSet<mdl_block_community> mdl_block_community { get; set; }
        public virtual DbSet<mdl_block_configurable_reports> mdl_block_configurable_reports { get; set; }
        public virtual DbSet<mdl_block_dof_events> mdl_block_dof_events { get; set; }
        public virtual DbSet<mdl_block_dof_plugins> mdl_block_dof_plugins { get; set; }
        public virtual DbSet<mdl_block_dof_s_accentryes> mdl_block_dof_s_accentryes { get; set; }
        public virtual DbSet<mdl_block_dof_s_accounts> mdl_block_dof_s_accounts { get; set; }
        public virtual DbSet<mdl_block_dof_s_achievementcats> mdl_block_dof_s_achievementcats { get; set; }
        public virtual DbSet<mdl_block_dof_s_achievementins> mdl_block_dof_s_achievementins { get; set; }
        public virtual DbSet<mdl_block_dof_s_achievements> mdl_block_dof_s_achievements { get; set; }
        public virtual DbSet<mdl_block_dof_s_acl> mdl_block_dof_s_acl { get; set; }
        public virtual DbSet<mdl_block_dof_s_aclwarrantagents> mdl_block_dof_s_aclwarrantagents { get; set; }
        public virtual DbSet<mdl_block_dof_s_aclwarrants> mdl_block_dof_s_aclwarrants { get; set; }
        public virtual DbSet<mdl_block_dof_s_addresses> mdl_block_dof_s_addresses { get; set; }
        public virtual DbSet<mdl_block_dof_s_ages> mdl_block_dof_s_ages { get; set; }
        public virtual DbSet<mdl_block_dof_s_agrouphistory> mdl_block_dof_s_agrouphistory { get; set; }
        public virtual DbSet<mdl_block_dof_s_agroups> mdl_block_dof_s_agroups { get; set; }
        public virtual DbSet<mdl_block_dof_s_appointments> mdl_block_dof_s_appointments { get; set; }
        public virtual DbSet<mdl_block_dof_s_comments> mdl_block_dof_s_comments { get; set; }
        public virtual DbSet<mdl_block_dof_s_config> mdl_block_dof_s_config { get; set; }
        public virtual DbSet<mdl_block_dof_s_contracts> mdl_block_dof_s_contracts { get; set; }
        public virtual DbSet<mdl_block_dof_s_cov> mdl_block_dof_s_cov { get; set; }
        public virtual DbSet<mdl_block_dof_s_cpassed> mdl_block_dof_s_cpassed { get; set; }
        public virtual DbSet<mdl_block_dof_s_cpgrades> mdl_block_dof_s_cpgrades { get; set; }
        public virtual DbSet<mdl_block_dof_s_cstreamlinks> mdl_block_dof_s_cstreamlinks { get; set; }
        public virtual DbSet<mdl_block_dof_s_cstreams> mdl_block_dof_s_cstreams { get; set; }
        public virtual DbSet<mdl_block_dof_s_departments> mdl_block_dof_s_departments { get; set; }
        public virtual DbSet<mdl_block_dof_s_eagreements> mdl_block_dof_s_eagreements { get; set; }
        public virtual DbSet<mdl_block_dof_s_educations> mdl_block_dof_s_educations { get; set; }
        public virtual DbSet<mdl_block_dof_s_invcategories> mdl_block_dof_s_invcategories { get; set; }
        public virtual DbSet<mdl_block_dof_s_invitems> mdl_block_dof_s_invitems { get; set; }
        public virtual DbSet<mdl_block_dof_s_invsets> mdl_block_dof_s_invsets { get; set; }
        public virtual DbSet<mdl_block_dof_s_learninghistory> mdl_block_dof_s_learninghistory { get; set; }
        public virtual DbSet<mdl_block_dof_s_learningplan> mdl_block_dof_s_learningplan { get; set; }
        public virtual DbSet<mdl_block_dof_s_metacontracts> mdl_block_dof_s_metacontracts { get; set; }
        public virtual DbSet<mdl_block_dof_s_orderdata> mdl_block_dof_s_orderdata { get; set; }
        public virtual DbSet<mdl_block_dof_s_orders> mdl_block_dof_s_orders { get; set; }
        public virtual DbSet<mdl_block_dof_s_organizations> mdl_block_dof_s_organizations { get; set; }
        public virtual DbSet<mdl_block_dof_s_persons> mdl_block_dof_s_persons { get; set; }
        public virtual DbSet<mdl_block_dof_s_planinh> mdl_block_dof_s_planinh { get; set; }
        public virtual DbSet<mdl_block_dof_s_plans> mdl_block_dof_s_plans { get; set; }
        public virtual DbSet<mdl_block_dof_s_plansections> mdl_block_dof_s_plansections { get; set; }
        public virtual DbSet<mdl_block_dof_s_positions> mdl_block_dof_s_positions { get; set; }
        public virtual DbSet<mdl_block_dof_s_pridepends> mdl_block_dof_s_pridepends { get; set; }
        public virtual DbSet<mdl_block_dof_s_programmitems> mdl_block_dof_s_programmitems { get; set; }
        public virtual DbSet<mdl_block_dof_s_programms> mdl_block_dof_s_programms { get; set; }
        public virtual DbSet<mdl_block_dof_s_programmsbcs> mdl_block_dof_s_programmsbcs { get; set; }
        public virtual DbSet<mdl_block_dof_s_reports> mdl_block_dof_s_reports { get; set; }
        public virtual DbSet<mdl_block_dof_s_schdays> mdl_block_dof_s_schdays { get; set; }
        public virtual DbSet<mdl_block_dof_s_schevents> mdl_block_dof_s_schevents { get; set; }
        public virtual DbSet<mdl_block_dof_s_schpositions> mdl_block_dof_s_schpositions { get; set; }
        public virtual DbSet<mdl_block_dof_s_schpresences> mdl_block_dof_s_schpresences { get; set; }
        public virtual DbSet<mdl_block_dof_s_schtemplates> mdl_block_dof_s_schtemplates { get; set; }
        public virtual DbSet<mdl_block_dof_s_skilllinks> mdl_block_dof_s_skilllinks { get; set; }
        public virtual DbSet<mdl_block_dof_s_skills> mdl_block_dof_s_skills { get; set; }
        public virtual DbSet<mdl_block_dof_s_statushistory> mdl_block_dof_s_statushistory { get; set; }
        public virtual DbSet<mdl_block_dof_s_sync> mdl_block_dof_s_sync { get; set; }
        public virtual DbSet<mdl_block_dof_s_synclogs> mdl_block_dof_s_synclogs { get; set; }
        public virtual DbSet<mdl_block_dof_s_taglinks> mdl_block_dof_s_taglinks { get; set; }
        public virtual DbSet<mdl_block_dof_s_tags> mdl_block_dof_s_tags { get; set; }
        public virtual DbSet<mdl_block_dof_s_tasks> mdl_block_dof_s_tasks { get; set; }
        public virtual DbSet<mdl_block_dof_s_teachers> mdl_block_dof_s_teachers { get; set; }
        public virtual DbSet<mdl_block_dof_s_workplaces> mdl_block_dof_s_workplaces { get; set; }
        public virtual DbSet<mdl_block_dof_todo> mdl_block_dof_todo { get; set; }
        public virtual DbSet<mdl_block_instances> mdl_block_instances { get; set; }
        public virtual DbSet<mdl_block_positions> mdl_block_positions { get; set; }
        public virtual DbSet<mdl_block_rate_course> mdl_block_rate_course { get; set; }
        public virtual DbSet<mdl_block_recent_activity> mdl_block_recent_activity { get; set; }
        public virtual DbSet<mdl_block_rss_client> mdl_block_rss_client { get; set; }
        public virtual DbSet<mdl_block_xp> mdl_block_xp { get; set; }
        public virtual DbSet<mdl_block_xp_config> mdl_block_xp_config { get; set; }
        public virtual DbSet<mdl_block_xp_filters> mdl_block_xp_filters { get; set; }
        public virtual DbSet<mdl_block_xp_log> mdl_block_xp_log { get; set; }
        public virtual DbSet<mdl_blog_association> mdl_blog_association { get; set; }
        public virtual DbSet<mdl_blog_external> mdl_blog_external { get; set; }
        public virtual DbSet<mdl_book> mdl_book { get; set; }
        public virtual DbSet<mdl_book_chapters> mdl_book_chapters { get; set; }
        public virtual DbSet<mdl_cache_filters> mdl_cache_filters { get; set; }
        public virtual DbSet<mdl_cache_flags> mdl_cache_flags { get; set; }
        public virtual DbSet<mdl_capabilities> mdl_capabilities { get; set; }
        public virtual DbSet<mdl_chat> mdl_chat { get; set; }
        public virtual DbSet<mdl_chat_messages> mdl_chat_messages { get; set; }
        public virtual DbSet<mdl_chat_messages_current> mdl_chat_messages_current { get; set; }
        public virtual DbSet<mdl_chat_users> mdl_chat_users { get; set; }
        public virtual DbSet<mdl_checklist> mdl_checklist { get; set; }
        public virtual DbSet<mdl_checklist_check> mdl_checklist_check { get; set; }
        public virtual DbSet<mdl_checklist_comment> mdl_checklist_comment { get; set; }
        public virtual DbSet<mdl_checklist_item> mdl_checklist_item { get; set; }
        public virtual DbSet<mdl_choice> mdl_choice { get; set; }
        public virtual DbSet<mdl_choice_answers> mdl_choice_answers { get; set; }
        public virtual DbSet<mdl_choice_options> mdl_choice_options { get; set; }
        public virtual DbSet<mdl_cohort> mdl_cohort { get; set; }
        public virtual DbSet<mdl_cohort_members> mdl_cohort_members { get; set; }
        public virtual DbSet<mdl_comdi> mdl_comdi { get; set; }
        public virtual DbSet<mdl_comdi_links> mdl_comdi_links { get; set; }
        public virtual DbSet<mdl_comments> mdl_comments { get; set; }
        public virtual DbSet<mdl_competency> mdl_competency { get; set; }
        public virtual DbSet<mdl_competency_coursecomp> mdl_competency_coursecomp { get; set; }
        public virtual DbSet<mdl_competency_coursecompsetting> mdl_competency_coursecompsetting { get; set; }
        public virtual DbSet<mdl_competency_evidence> mdl_competency_evidence { get; set; }
        public virtual DbSet<mdl_competency_framework> mdl_competency_framework { get; set; }
        public virtual DbSet<mdl_competency_modulecomp> mdl_competency_modulecomp { get; set; }
        public virtual DbSet<mdl_competency_plan> mdl_competency_plan { get; set; }
        public virtual DbSet<mdl_competency_plancomp> mdl_competency_plancomp { get; set; }
        public virtual DbSet<mdl_competency_relatedcomp> mdl_competency_relatedcomp { get; set; }
        public virtual DbSet<mdl_competency_template> mdl_competency_template { get; set; }
        public virtual DbSet<mdl_competency_templatecohort> mdl_competency_templatecohort { get; set; }
        public virtual DbSet<mdl_competency_templatecomp> mdl_competency_templatecomp { get; set; }
        public virtual DbSet<mdl_competency_usercomp> mdl_competency_usercomp { get; set; }
        public virtual DbSet<mdl_competency_usercompcourse> mdl_competency_usercompcourse { get; set; }
        public virtual DbSet<mdl_competency_usercompplan> mdl_competency_usercompplan { get; set; }
        public virtual DbSet<mdl_competency_userevidence> mdl_competency_userevidence { get; set; }
        public virtual DbSet<mdl_competency_userevidencecomp> mdl_competency_userevidencecomp { get; set; }
        public virtual DbSet<mdl_config> mdl_config { get; set; }
        public virtual DbSet<mdl_config_log> mdl_config_log { get; set; }
        public virtual DbSet<mdl_config_plugins> mdl_config_plugins { get; set; }
        public virtual DbSet<mdl_context> mdl_context { get; set; }
        public virtual DbSet<mdl_context_temp> mdl_context_temp { get; set; }
        public virtual DbSet<mdl_course> mdl_course { get; set; }
        public virtual DbSet<mdl_course_categories> mdl_course_categories { get; set; }
        public virtual DbSet<mdl_course_completion_aggr_methd> mdl_course_completion_aggr_methd { get; set; }
        public virtual DbSet<mdl_course_completion_crit_compl> mdl_course_completion_crit_compl { get; set; }
        public virtual DbSet<mdl_course_completion_criteria> mdl_course_completion_criteria { get; set; }
        public virtual DbSet<mdl_course_completions> mdl_course_completions { get; set; }
        public virtual DbSet<mdl_course_format_options> mdl_course_format_options { get; set; }
        public virtual DbSet<mdl_course_modules> mdl_course_modules { get; set; }
        public virtual DbSet<mdl_course_modules_completion> mdl_course_modules_completion { get; set; }
        public virtual DbSet<mdl_course_published> mdl_course_published { get; set; }
        public virtual DbSet<mdl_course_request> mdl_course_request { get; set; }
        public virtual DbSet<mdl_course_sections> mdl_course_sections { get; set; }
        public virtual DbSet<mdl_crw_category_properties> mdl_crw_category_properties { get; set; }
        public virtual DbSet<mdl_crw_course_properties> mdl_crw_course_properties { get; set; }
        public virtual DbSet<mdl_data> mdl_data { get; set; }
        public virtual DbSet<mdl_data_content> mdl_data_content { get; set; }
        public virtual DbSet<mdl_data_fields> mdl_data_fields { get; set; }
        public virtual DbSet<mdl_data_records> mdl_data_records { get; set; }
        public virtual DbSet<mdl_editor_atto_autosave> mdl_editor_atto_autosave { get; set; }
        public virtual DbSet<mdl_enrol> mdl_enrol { get; set; }
        public virtual DbSet<mdl_enrol_flatfile> mdl_enrol_flatfile { get; set; }
        public virtual DbSet<mdl_enrol_lti_tools> mdl_enrol_lti_tools { get; set; }
        public virtual DbSet<mdl_enrol_lti_users> mdl_enrol_lti_users { get; set; }
        public virtual DbSet<mdl_enrol_otpay> mdl_enrol_otpay { get; set; }
        public virtual DbSet<mdl_enrol_otpay_coupon_cat> mdl_enrol_otpay_coupon_cat { get; set; }
        public virtual DbSet<mdl_enrol_otpay_coupon_log> mdl_enrol_otpay_coupon_log { get; set; }
        public virtual DbSet<mdl_enrol_otpay_coupons> mdl_enrol_otpay_coupons { get; set; }
        public virtual DbSet<mdl_enrol_otpay_log> mdl_enrol_otpay_log { get; set; }
        public virtual DbSet<mdl_enrol_paypal> mdl_enrol_paypal { get; set; }
        public virtual DbSet<mdl_enrol_sitecall> mdl_enrol_sitecall { get; set; }
        public virtual DbSet<mdl_event> mdl_event { get; set; }
        public virtual DbSet<mdl_event_subscriptions> mdl_event_subscriptions { get; set; }
        public virtual DbSet<mdl_events_handlers> mdl_events_handlers { get; set; }
        public virtual DbSet<mdl_events_queue> mdl_events_queue { get; set; }
        public virtual DbSet<mdl_events_queue_handlers> mdl_events_queue_handlers { get; set; }
        public virtual DbSet<mdl_external_functions> mdl_external_functions { get; set; }
        public virtual DbSet<mdl_external_services> mdl_external_services { get; set; }
        public virtual DbSet<mdl_external_services_functions> mdl_external_services_functions { get; set; }
        public virtual DbSet<mdl_external_services_users> mdl_external_services_users { get; set; }
        public virtual DbSet<mdl_external_tokens> mdl_external_tokens { get; set; }
        public virtual DbSet<mdl_feedback> mdl_feedback { get; set; }
        public virtual DbSet<mdl_feedback_completed> mdl_feedback_completed { get; set; }
        public virtual DbSet<mdl_feedback_completedtmp> mdl_feedback_completedtmp { get; set; }
        public virtual DbSet<mdl_feedback_item> mdl_feedback_item { get; set; }
        public virtual DbSet<mdl_feedback_sitecourse_map> mdl_feedback_sitecourse_map { get; set; }
        public virtual DbSet<mdl_feedback_template> mdl_feedback_template { get; set; }
        public virtual DbSet<mdl_feedback_value> mdl_feedback_value { get; set; }
        public virtual DbSet<mdl_feedback_valuetmp> mdl_feedback_valuetmp { get; set; }
        public virtual DbSet<mdl_files> mdl_files { get; set; }
        public virtual DbSet<mdl_files_reference> mdl_files_reference { get; set; }
        public virtual DbSet<mdl_filter_active> mdl_filter_active { get; set; }
        public virtual DbSet<mdl_filter_config> mdl_filter_config { get; set; }
        public virtual DbSet<mdl_folder> mdl_folder { get; set; }
        public virtual DbSet<mdl_format_grid_icon> mdl_format_grid_icon { get; set; }
        public virtual DbSet<mdl_format_grid_summary> mdl_format_grid_summary { get; set; }
        public virtual DbSet<mdl_forum> mdl_forum { get; set; }
        public virtual DbSet<mdl_forum_digests> mdl_forum_digests { get; set; }
        public virtual DbSet<mdl_forum_discussion_subs> mdl_forum_discussion_subs { get; set; }
        public virtual DbSet<mdl_forum_discussions> mdl_forum_discussions { get; set; }
        public virtual DbSet<mdl_forum_posts> mdl_forum_posts { get; set; }
        public virtual DbSet<mdl_forum_queue> mdl_forum_queue { get; set; }
        public virtual DbSet<mdl_forum_read> mdl_forum_read { get; set; }
        public virtual DbSet<mdl_forum_subscriptions> mdl_forum_subscriptions { get; set; }
        public virtual DbSet<mdl_forum_track_prefs> mdl_forum_track_prefs { get; set; }
        public virtual DbSet<mdl_glossary> mdl_glossary { get; set; }
        public virtual DbSet<mdl_glossary_alias> mdl_glossary_alias { get; set; }
        public virtual DbSet<mdl_glossary_categories> mdl_glossary_categories { get; set; }
        public virtual DbSet<mdl_glossary_entries> mdl_glossary_entries { get; set; }
        public virtual DbSet<mdl_glossary_entries_categories> mdl_glossary_entries_categories { get; set; }
        public virtual DbSet<mdl_glossary_formats> mdl_glossary_formats { get; set; }
        public virtual DbSet<mdl_grade_categories> mdl_grade_categories { get; set; }
        public virtual DbSet<mdl_grade_categories_history> mdl_grade_categories_history { get; set; }
        public virtual DbSet<mdl_grade_grades> mdl_grade_grades { get; set; }
        public virtual DbSet<mdl_grade_grades_history> mdl_grade_grades_history { get; set; }
        public virtual DbSet<mdl_grade_import_newitem> mdl_grade_import_newitem { get; set; }
        public virtual DbSet<mdl_grade_import_values> mdl_grade_import_values { get; set; }
        public virtual DbSet<mdl_grade_items> mdl_grade_items { get; set; }
        public virtual DbSet<mdl_grade_items_history> mdl_grade_items_history { get; set; }
        public virtual DbSet<mdl_grade_letters> mdl_grade_letters { get; set; }
        public virtual DbSet<mdl_grade_outcomes> mdl_grade_outcomes { get; set; }
        public virtual DbSet<mdl_grade_outcomes_courses> mdl_grade_outcomes_courses { get; set; }
        public virtual DbSet<mdl_grade_outcomes_history> mdl_grade_outcomes_history { get; set; }
        public virtual DbSet<mdl_grade_settings> mdl_grade_settings { get; set; }
        public virtual DbSet<mdl_grading_areas> mdl_grading_areas { get; set; }
        public virtual DbSet<mdl_grading_definitions> mdl_grading_definitions { get; set; }
        public virtual DbSet<mdl_grading_instances> mdl_grading_instances { get; set; }
        public virtual DbSet<mdl_gradingform_guide_comments> mdl_gradingform_guide_comments { get; set; }
        public virtual DbSet<mdl_gradingform_guide_criteria> mdl_gradingform_guide_criteria { get; set; }
        public virtual DbSet<mdl_gradingform_guide_fillings> mdl_gradingform_guide_fillings { get; set; }
        public virtual DbSet<mdl_gradingform_rubric_criteria> mdl_gradingform_rubric_criteria { get; set; }
        public virtual DbSet<mdl_gradingform_rubric_fillings> mdl_gradingform_rubric_fillings { get; set; }
        public virtual DbSet<mdl_gradingform_rubric_levels> mdl_gradingform_rubric_levels { get; set; }
        public virtual DbSet<mdl_groupings> mdl_groupings { get; set; }
        public virtual DbSet<mdl_groupings_groups> mdl_groupings_groups { get; set; }
        public virtual DbSet<mdl_groups> mdl_groups { get; set; }
        public virtual DbSet<mdl_groups_members> mdl_groups_members { get; set; }
        public virtual DbSet<mdl_hotpot> mdl_hotpot { get; set; }
        public virtual DbSet<mdl_hotpot_attempts> mdl_hotpot_attempts { get; set; }
        public virtual DbSet<mdl_hotpot_cache> mdl_hotpot_cache { get; set; }
        public virtual DbSet<mdl_hotpot_details> mdl_hotpot_details { get; set; }
        public virtual DbSet<mdl_hotpot_questions> mdl_hotpot_questions { get; set; }
        public virtual DbSet<mdl_hotpot_responses> mdl_hotpot_responses { get; set; }
        public virtual DbSet<mdl_hotpot_strings> mdl_hotpot_strings { get; set; }
        public virtual DbSet<mdl_imscp> mdl_imscp { get; set; }
        public virtual DbSet<mdl_label> mdl_label { get; set; }
        public virtual DbSet<mdl_lesson> mdl_lesson { get; set; }
        public virtual DbSet<mdl_lesson_answers> mdl_lesson_answers { get; set; }
        public virtual DbSet<mdl_lesson_attempts> mdl_lesson_attempts { get; set; }
        public virtual DbSet<mdl_lesson_branch> mdl_lesson_branch { get; set; }
        public virtual DbSet<mdl_lesson_grades> mdl_lesson_grades { get; set; }
        public virtual DbSet<mdl_lesson_overrides> mdl_lesson_overrides { get; set; }
        public virtual DbSet<mdl_lesson_pages> mdl_lesson_pages { get; set; }
        public virtual DbSet<mdl_lesson_timer> mdl_lesson_timer { get; set; }
        public virtual DbSet<mdl_license> mdl_license { get; set; }
        public virtual DbSet<mdl_local_intelliboard_logs> mdl_local_intelliboard_logs { get; set; }
        public virtual DbSet<mdl_local_intelliboard_totals> mdl_local_intelliboard_totals { get; set; }
        public virtual DbSet<mdl_local_intelliboard_tracking> mdl_local_intelliboard_tracking { get; set; }
        public virtual DbSet<mdl_local_learninghistory> mdl_local_learninghistory { get; set; }
        public virtual DbSet<mdl_lock_db> mdl_lock_db { get; set; }
        public virtual DbSet<mdl_log> mdl_log { get; set; }
        public virtual DbSet<mdl_log_display> mdl_log_display { get; set; }
        public virtual DbSet<mdl_log_queries> mdl_log_queries { get; set; }
        public virtual DbSet<mdl_logstore_standard_log> mdl_logstore_standard_log { get; set; }
        public virtual DbSet<mdl_lti> mdl_lti { get; set; }
        public virtual DbSet<mdl_lti_submission> mdl_lti_submission { get; set; }
        public virtual DbSet<mdl_lti_tool_proxies> mdl_lti_tool_proxies { get; set; }
        public virtual DbSet<mdl_lti_tool_settings> mdl_lti_tool_settings { get; set; }
        public virtual DbSet<mdl_lti_types> mdl_lti_types { get; set; }
        public virtual DbSet<mdl_lti_types_config> mdl_lti_types_config { get; set; }
        public virtual DbSet<mdl_message> mdl_message { get; set; }
        public virtual DbSet<mdl_message_airnotifier_devices> mdl_message_airnotifier_devices { get; set; }
        public virtual DbSet<mdl_message_contacts> mdl_message_contacts { get; set; }
        public virtual DbSet<mdl_message_processors> mdl_message_processors { get; set; }
        public virtual DbSet<mdl_message_providers> mdl_message_providers { get; set; }
        public virtual DbSet<mdl_message_read> mdl_message_read { get; set; }
        public virtual DbSet<mdl_message_working> mdl_message_working { get; set; }
        public virtual DbSet<mdl_messageinbound_datakeys> mdl_messageinbound_datakeys { get; set; }
        public virtual DbSet<mdl_messageinbound_handlers> mdl_messageinbound_handlers { get; set; }
        public virtual DbSet<mdl_messageinbound_messagelist> mdl_messageinbound_messagelist { get; set; }
        public virtual DbSet<mdl_mnet_application> mdl_mnet_application { get; set; }
        public virtual DbSet<mdl_mnet_host> mdl_mnet_host { get; set; }
        public virtual DbSet<mdl_mnet_host2service> mdl_mnet_host2service { get; set; }
        public virtual DbSet<mdl_mnet_log> mdl_mnet_log { get; set; }
        public virtual DbSet<mdl_mnet_remote_rpc> mdl_mnet_remote_rpc { get; set; }
        public virtual DbSet<mdl_mnet_remote_service2rpc> mdl_mnet_remote_service2rpc { get; set; }
        public virtual DbSet<mdl_mnet_rpc> mdl_mnet_rpc { get; set; }
        public virtual DbSet<mdl_mnet_service> mdl_mnet_service { get; set; }
        public virtual DbSet<mdl_mnet_service2rpc> mdl_mnet_service2rpc { get; set; }
        public virtual DbSet<mdl_mnet_session> mdl_mnet_session { get; set; }
        public virtual DbSet<mdl_mnet_sso_access_control> mdl_mnet_sso_access_control { get; set; }
        public virtual DbSet<mdl_mnetservice_enrol_courses> mdl_mnetservice_enrol_courses { get; set; }
        public virtual DbSet<mdl_mnetservice_enrol_enrolments> mdl_mnetservice_enrol_enrolments { get; set; }
        public virtual DbSet<mdl_modules> mdl_modules { get; set; }
        public virtual DbSet<mdl_my_pages> mdl_my_pages { get; set; }
        public virtual DbSet<mdl_oauth_access_tokens> mdl_oauth_access_tokens { get; set; }
        public virtual DbSet<mdl_oauth_authorization_codes> mdl_oauth_authorization_codes { get; set; }
        public virtual DbSet<mdl_oauth_clients> mdl_oauth_clients { get; set; }
        public virtual DbSet<mdl_oauth_jwt> mdl_oauth_jwt { get; set; }
        public virtual DbSet<mdl_oauth_public_keys> mdl_oauth_public_keys { get; set; }
        public virtual DbSet<mdl_oauth_refresh_tokens> mdl_oauth_refresh_tokens { get; set; }
        public virtual DbSet<mdl_oauth_scopes> mdl_oauth_scopes { get; set; }
        public virtual DbSet<mdl_oauth_user_auth_scopes> mdl_oauth_user_auth_scopes { get; set; }
        public virtual DbSet<mdl_offlinequiz> mdl_offlinequiz { get; set; }
        public virtual DbSet<mdl_offlinequiz_attempts> mdl_offlinequiz_attempts { get; set; }
        public virtual DbSet<mdl_offlinequiz_choices> mdl_offlinequiz_choices { get; set; }
        public virtual DbSet<mdl_offlinequiz_group_questions> mdl_offlinequiz_group_questions { get; set; }
        public virtual DbSet<mdl_offlinequiz_groups> mdl_offlinequiz_groups { get; set; }
        public virtual DbSet<mdl_offlinequiz_hotspots> mdl_offlinequiz_hotspots { get; set; }
        public virtual DbSet<mdl_offlinequiz_p_choices> mdl_offlinequiz_p_choices { get; set; }
        public virtual DbSet<mdl_offlinequiz_p_lists> mdl_offlinequiz_p_lists { get; set; }
        public virtual DbSet<mdl_offlinequiz_page_corners> mdl_offlinequiz_page_corners { get; set; }
        public virtual DbSet<mdl_offlinequiz_participants> mdl_offlinequiz_participants { get; set; }
        public virtual DbSet<mdl_offlinequiz_q_response_stats> mdl_offlinequiz_q_response_stats { get; set; }
        public virtual DbSet<mdl_offlinequiz_q_statistics> mdl_offlinequiz_q_statistics { get; set; }
        public virtual DbSet<mdl_offlinequiz_queue> mdl_offlinequiz_queue { get; set; }
        public virtual DbSet<mdl_offlinequiz_queue_data> mdl_offlinequiz_queue_data { get; set; }
        public virtual DbSet<mdl_offlinequiz_reports> mdl_offlinequiz_reports { get; set; }
        public virtual DbSet<mdl_offlinequiz_results> mdl_offlinequiz_results { get; set; }
        public virtual DbSet<mdl_offlinequiz_scanned_p_pages> mdl_offlinequiz_scanned_p_pages { get; set; }
        public virtual DbSet<mdl_offlinequiz_scanned_pages> mdl_offlinequiz_scanned_pages { get; set; }
        public virtual DbSet<mdl_offlinequiz_statistics> mdl_offlinequiz_statistics { get; set; }
        public virtual DbSet<mdl_openmeetings> mdl_openmeetings { get; set; }
        public virtual DbSet<mdl_otcourselogic> mdl_otcourselogic { get; set; }
        public virtual DbSet<mdl_otcourselogic_state> mdl_otcourselogic_state { get; set; }
        public virtual DbSet<mdl_page> mdl_page { get; set; }
        public virtual DbSet<mdl_plagiarism_apru_config> mdl_plagiarism_apru_config { get; set; }
        public virtual DbSet<mdl_plagiarism_apru_files> mdl_plagiarism_apru_files { get; set; }
        public virtual DbSet<mdl_plagiarism_rucont_config> mdl_plagiarism_rucont_config { get; set; }
        public virtual DbSet<mdl_plagiarism_rucont_files> mdl_plagiarism_rucont_files { get; set; }
        public virtual DbSet<mdl_portfolio_instance> mdl_portfolio_instance { get; set; }
        public virtual DbSet<mdl_portfolio_instance_config> mdl_portfolio_instance_config { get; set; }
        public virtual DbSet<mdl_portfolio_instance_user> mdl_portfolio_instance_user { get; set; }
        public virtual DbSet<mdl_portfolio_log> mdl_portfolio_log { get; set; }
        public virtual DbSet<mdl_portfolio_mahara_queue> mdl_portfolio_mahara_queue { get; set; }
        public virtual DbSet<mdl_portfolio_tempdata> mdl_portfolio_tempdata { get; set; }
        public virtual DbSet<mdl_post> mdl_post { get; set; }
        public virtual DbSet<mdl_profiling> mdl_profiling { get; set; }
        public virtual DbSet<mdl_qtype_ddimageortext> mdl_qtype_ddimageortext { get; set; }
        public virtual DbSet<mdl_qtype_ddimageortext_drags> mdl_qtype_ddimageortext_drags { get; set; }
        public virtual DbSet<mdl_qtype_ddimageortext_drops> mdl_qtype_ddimageortext_drops { get; set; }
        public virtual DbSet<mdl_qtype_ddmarker> mdl_qtype_ddmarker { get; set; }
        public virtual DbSet<mdl_qtype_ddmarker_drags> mdl_qtype_ddmarker_drags { get; set; }
        public virtual DbSet<mdl_qtype_ddmarker_drops> mdl_qtype_ddmarker_drops { get; set; }
        public virtual DbSet<mdl_qtype_ddmatch_options> mdl_qtype_ddmatch_options { get; set; }
        public virtual DbSet<mdl_qtype_ddmatch_subquestions> mdl_qtype_ddmatch_subquestions { get; set; }
        public virtual DbSet<mdl_qtype_essay_options> mdl_qtype_essay_options { get; set; }
        public virtual DbSet<mdl_qtype_match_options> mdl_qtype_match_options { get; set; }
        public virtual DbSet<mdl_qtype_match_subquestions> mdl_qtype_match_subquestions { get; set; }
        public virtual DbSet<mdl_qtype_multichoice_options> mdl_qtype_multichoice_options { get; set; }
        public virtual DbSet<mdl_qtype_ordering_options> mdl_qtype_ordering_options { get; set; }
        public virtual DbSet<mdl_qtype_randomsamatch_options> mdl_qtype_randomsamatch_options { get; set; }
        public virtual DbSet<mdl_qtype_shortanswer_options> mdl_qtype_shortanswer_options { get; set; }
        public virtual DbSet<mdl_question> mdl_question { get; set; }
        public virtual DbSet<mdl_question_answers> mdl_question_answers { get; set; }
        public virtual DbSet<mdl_question_attempt_step_data> mdl_question_attempt_step_data { get; set; }
        public virtual DbSet<mdl_question_attempt_steps> mdl_question_attempt_steps { get; set; }
        public virtual DbSet<mdl_question_attempts> mdl_question_attempts { get; set; }
        public virtual DbSet<mdl_question_calculated> mdl_question_calculated { get; set; }
        public virtual DbSet<mdl_question_calculated_options> mdl_question_calculated_options { get; set; }
        public virtual DbSet<mdl_question_categories> mdl_question_categories { get; set; }
        public virtual DbSet<mdl_question_dataset_definitions> mdl_question_dataset_definitions { get; set; }
        public virtual DbSet<mdl_question_dataset_items> mdl_question_dataset_items { get; set; }
        public virtual DbSet<mdl_question_datasets> mdl_question_datasets { get; set; }
        public virtual DbSet<mdl_question_ddwtos> mdl_question_ddwtos { get; set; }
        public virtual DbSet<mdl_question_gapselect> mdl_question_gapselect { get; set; }
        public virtual DbSet<mdl_question_hints> mdl_question_hints { get; set; }
        public virtual DbSet<mdl_question_multianswer> mdl_question_multianswer { get; set; }
        public virtual DbSet<mdl_question_numerical> mdl_question_numerical { get; set; }
        public virtual DbSet<mdl_question_numerical_options> mdl_question_numerical_options { get; set; }
        public virtual DbSet<mdl_question_numerical_units> mdl_question_numerical_units { get; set; }
        public virtual DbSet<mdl_question_response_analysis> mdl_question_response_analysis { get; set; }
        public virtual DbSet<mdl_question_response_count> mdl_question_response_count { get; set; }
        public virtual DbSet<mdl_question_statistics> mdl_question_statistics { get; set; }
        public virtual DbSet<mdl_question_truefalse> mdl_question_truefalse { get; set; }
        public virtual DbSet<mdl_question_usages> mdl_question_usages { get; set; }
        public virtual DbSet<mdl_quiz> mdl_quiz { get; set; }
        public virtual DbSet<mdl_quiz_attempts> mdl_quiz_attempts { get; set; }
        public virtual DbSet<mdl_quiz_feedback> mdl_quiz_feedback { get; set; }
        public virtual DbSet<mdl_quiz_grades> mdl_quiz_grades { get; set; }
        public virtual DbSet<mdl_quiz_overrides> mdl_quiz_overrides { get; set; }
        public virtual DbSet<mdl_quiz_overview_regrades> mdl_quiz_overview_regrades { get; set; }
        public virtual DbSet<mdl_quiz_reports> mdl_quiz_reports { get; set; }
        public virtual DbSet<mdl_quiz_sections> mdl_quiz_sections { get; set; }
        public virtual DbSet<mdl_quiz_slots> mdl_quiz_slots { get; set; }
        public virtual DbSet<mdl_quiz_statistics> mdl_quiz_statistics { get; set; }
        public virtual DbSet<mdl_rating> mdl_rating { get; set; }
        public virtual DbSet<mdl_recordingsbn> mdl_recordingsbn { get; set; }
        public virtual DbSet<mdl_registration_hubs> mdl_registration_hubs { get; set; }
        public virtual DbSet<mdl_repository> mdl_repository { get; set; }
        public virtual DbSet<mdl_repository_instance_config> mdl_repository_instance_config { get; set; }
        public virtual DbSet<mdl_repository_instances> mdl_repository_instances { get; set; }
        public virtual DbSet<mdl_resource> mdl_resource { get; set; }
        public virtual DbSet<mdl_resource_old> mdl_resource_old { get; set; }
        public virtual DbSet<mdl_role> mdl_role { get; set; }
        public virtual DbSet<mdl_role_allow_assign> mdl_role_allow_assign { get; set; }
        public virtual DbSet<mdl_role_allow_override> mdl_role_allow_override { get; set; }
        public virtual DbSet<mdl_role_allow_switch> mdl_role_allow_switch { get; set; }
        public virtual DbSet<mdl_role_assignments> mdl_role_assignments { get; set; }
        public virtual DbSet<mdl_role_capabilities> mdl_role_capabilities { get; set; }
        public virtual DbSet<mdl_role_context_levels> mdl_role_context_levels { get; set; }
        public virtual DbSet<mdl_role_names> mdl_role_names { get; set; }
        public virtual DbSet<mdl_role_sortorder> mdl_role_sortorder { get; set; }
        public virtual DbSet<mdl_rucontbook> mdl_rucontbook { get; set; }
        public virtual DbSet<mdl_scale> mdl_scale { get; set; }
        public virtual DbSet<mdl_scale_history> mdl_scale_history { get; set; }
        public virtual DbSet<mdl_scorm> mdl_scorm { get; set; }
        public virtual DbSet<mdl_scorm_aicc_session> mdl_scorm_aicc_session { get; set; }
        public virtual DbSet<mdl_scorm_scoes> mdl_scorm_scoes { get; set; }
        public virtual DbSet<mdl_scorm_scoes_data> mdl_scorm_scoes_data { get; set; }
        public virtual DbSet<mdl_scorm_scoes_track> mdl_scorm_scoes_track { get; set; }
        public virtual DbSet<mdl_scorm_seq_mapinfo> mdl_scorm_seq_mapinfo { get; set; }
        public virtual DbSet<mdl_scorm_seq_objective> mdl_scorm_seq_objective { get; set; }
        public virtual DbSet<mdl_scorm_seq_rolluprule> mdl_scorm_seq_rolluprule { get; set; }
        public virtual DbSet<mdl_scorm_seq_rolluprulecond> mdl_scorm_seq_rolluprulecond { get; set; }
        public virtual DbSet<mdl_scorm_seq_rulecond> mdl_scorm_seq_rulecond { get; set; }
        public virtual DbSet<mdl_scorm_seq_ruleconds> mdl_scorm_seq_ruleconds { get; set; }
        public virtual DbSet<mdl_sessions> mdl_sessions { get; set; }
        public virtual DbSet<mdl_simplecertificate> mdl_simplecertificate { get; set; }
        public virtual DbSet<mdl_simplecertificate_issues> mdl_simplecertificate_issues { get; set; }
        public virtual DbSet<mdl_stats_daily> mdl_stats_daily { get; set; }
        public virtual DbSet<mdl_stats_monthly> mdl_stats_monthly { get; set; }
        public virtual DbSet<mdl_stats_user_daily> mdl_stats_user_daily { get; set; }
        public virtual DbSet<mdl_stats_user_monthly> mdl_stats_user_monthly { get; set; }
        public virtual DbSet<mdl_stats_user_weekly> mdl_stats_user_weekly { get; set; }
        public virtual DbSet<mdl_stats_weekly> mdl_stats_weekly { get; set; }
        public virtual DbSet<mdl_subcourse> mdl_subcourse { get; set; }
        public virtual DbSet<mdl_survey> mdl_survey { get; set; }
        public virtual DbSet<mdl_survey_analysis> mdl_survey_analysis { get; set; }
        public virtual DbSet<mdl_survey_answers> mdl_survey_answers { get; set; }
        public virtual DbSet<mdl_survey_questions> mdl_survey_questions { get; set; }
        public virtual DbSet<mdl_tag> mdl_tag { get; set; }
        public virtual DbSet<mdl_tag_area> mdl_tag_area { get; set; }
        public virtual DbSet<mdl_tag_coll> mdl_tag_coll { get; set; }
        public virtual DbSet<mdl_tag_correlation> mdl_tag_correlation { get; set; }
        public virtual DbSet<mdl_tag_instance> mdl_tag_instance { get; set; }
        public virtual DbSet<mdl_task_adhoc> mdl_task_adhoc { get; set; }
        public virtual DbSet<mdl_task_scheduled> mdl_task_scheduled { get; set; }
        public virtual DbSet<mdl_tool_cohortroles> mdl_tool_cohortroles { get; set; }
        public virtual DbSet<mdl_tool_customlang> mdl_tool_customlang { get; set; }
        public virtual DbSet<mdl_tool_customlang_components> mdl_tool_customlang_components { get; set; }
        public virtual DbSet<mdl_tool_monitor_events> mdl_tool_monitor_events { get; set; }
        public virtual DbSet<mdl_tool_monitor_history> mdl_tool_monitor_history { get; set; }
        public virtual DbSet<mdl_tool_monitor_rules> mdl_tool_monitor_rules { get; set; }
        public virtual DbSet<mdl_tool_monitor_subscriptions> mdl_tool_monitor_subscriptions { get; set; }
        public virtual DbSet<mdl_tool_recyclebin_category> mdl_tool_recyclebin_category { get; set; }
        public virtual DbSet<mdl_tool_recyclebin_course> mdl_tool_recyclebin_course { get; set; }
        public virtual DbSet<mdl_upgrade_log> mdl_upgrade_log { get; set; }
        public virtual DbSet<mdl_url> mdl_url { get; set; }
        public virtual DbSet<mdl_user> mdl_user { get; set; }
        public virtual DbSet<mdl_user_devices> mdl_user_devices { get; set; }
        public virtual DbSet<mdl_user_enrolments> mdl_user_enrolments { get; set; }
        public virtual DbSet<mdl_user_info_category> mdl_user_info_category { get; set; }
        public virtual DbSet<mdl_user_info_data> mdl_user_info_data { get; set; }
        public virtual DbSet<mdl_user_info_field> mdl_user_info_field { get; set; }
        public virtual DbSet<mdl_user_lastaccess> mdl_user_lastaccess { get; set; }
        public virtual DbSet<mdl_user_password_history> mdl_user_password_history { get; set; }
        public virtual DbSet<mdl_user_password_resets> mdl_user_password_resets { get; set; }
        public virtual DbSet<mdl_user_preferences> mdl_user_preferences { get; set; }
        public virtual DbSet<mdl_user_private_key> mdl_user_private_key { get; set; }
        public virtual DbSet<mdl_wiki> mdl_wiki { get; set; }
        public virtual DbSet<mdl_wiki_links> mdl_wiki_links { get; set; }
        public virtual DbSet<mdl_wiki_locks> mdl_wiki_locks { get; set; }
        public virtual DbSet<mdl_wiki_pages> mdl_wiki_pages { get; set; }
        public virtual DbSet<mdl_wiki_subwikis> mdl_wiki_subwikis { get; set; }
        public virtual DbSet<mdl_wiki_synonyms> mdl_wiki_synonyms { get; set; }
        public virtual DbSet<mdl_wiki_versions> mdl_wiki_versions { get; set; }
        public virtual DbSet<mdl_wiziq> mdl_wiziq { get; set; }
        public virtual DbSet<mdl_wiziq_content> mdl_wiziq_content { get; set; }
        public virtual DbSet<mdl_workshop> mdl_workshop { get; set; }
        public virtual DbSet<mdl_workshop_aggregations> mdl_workshop_aggregations { get; set; }
        public virtual DbSet<mdl_workshop_assessments> mdl_workshop_assessments { get; set; }
        public virtual DbSet<mdl_workshop_assessments_old> mdl_workshop_assessments_old { get; set; }
        public virtual DbSet<mdl_workshop_comments_old> mdl_workshop_comments_old { get; set; }
        public virtual DbSet<mdl_workshop_elements_old> mdl_workshop_elements_old { get; set; }
        public virtual DbSet<mdl_workshop_grades> mdl_workshop_grades { get; set; }
        public virtual DbSet<mdl_workshop_grades_old> mdl_workshop_grades_old { get; set; }
        public virtual DbSet<mdl_workshop_old> mdl_workshop_old { get; set; }
        public virtual DbSet<mdl_workshop_rubrics_old> mdl_workshop_rubrics_old { get; set; }
        public virtual DbSet<mdl_workshop_stockcomments_old> mdl_workshop_stockcomments_old { get; set; }
        public virtual DbSet<mdl_workshop_submissions> mdl_workshop_submissions { get; set; }
        public virtual DbSet<mdl_workshop_submissions_old> mdl_workshop_submissions_old { get; set; }
        public virtual DbSet<mdl_workshopallocation_scheduled> mdl_workshopallocation_scheduled { get; set; }
        public virtual DbSet<mdl_workshopeval_best_settings> mdl_workshopeval_best_settings { get; set; }
        public virtual DbSet<mdl_workshopform_accumulative> mdl_workshopform_accumulative { get; set; }
        public virtual DbSet<mdl_workshopform_comments> mdl_workshopform_comments { get; set; }
        public virtual DbSet<mdl_workshopform_numerrors> mdl_workshopform_numerrors { get; set; }
        public virtual DbSet<mdl_workshopform_numerrors_map> mdl_workshopform_numerrors_map { get; set; }
        public virtual DbSet<mdl_workshopform_rubric> mdl_workshopform_rubric { get; set; }
        public virtual DbSet<mdl_workshopform_rubric_config> mdl_workshopform_rubric_config { get; set; }
        public virtual DbSet<mdl_workshopform_rubric_levels> mdl_workshopform_rubric_levels { get; set; }
    }
}